-i-m-p-o-r-t- -L-i-n-k- -f-r-o-m- -"-n-e-x-t-/-l-i-n-k-"-;-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -f-u-n-c-t-i-o-n- -P-a-y-m-e-n-t-C-a-n-c-e-l-P-a-g-e-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-x---a-u-t-o- -m-a-x---w---3-x-l- -p-x---4- -p-y---1-6-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-c-a-r-d- -p---8-"->-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-b-a-d-g-e-"->-C-h-e-c-k-o-u-t- -c-a-n-c-e-l-l-e-d-<-/-p->-
- - - - - - - - -<-h-1- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -t-e-x-t---3-x-l- -f-o-n-t---b-o-l-d-"->-N-o- -p-a-y-m-e-n-t- -w-a-s- -c-o-m-p-l-e-t-e-d-.-<-/-h-1->-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---s-l-a-t-e---6-0-0-"->-Y-o-u- -c-a-n- -r-e-t-u-r-n- -t-o- -t-h-e- -c-a-t-a-l-o-g- -a-n-d- -t-r-y- -a-g-a-i-n- -w-h-e-n-e-v-e-r- -y-o-u- -a-r-e- -r-e-a-d-y-.-<-/-p->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -f-l-e-x- -g-a-p---3-"->-
- - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-c-o-u-r-s-e-s-"- -c-l-a-s-s-N-a-m-e-=-"-b-t-n---p-r-i-m-a-r-y-"->-B-r-o-w-s-e- -c-o-u-r-s-e-s-<-/-L-i-n-k->-
- - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-w-o-r-k-s-h-o-p-s-"- -c-l-a-s-s-N-a-m-e-=-"-b-t-n---l-i-g-h-t-"->-B-r-o-w-s-e- -w-o-r-k-s-h-o-p-s-<-/-L-i-n-k->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-