-i-m-p-o-r-t- -{- -r-e-d-i-r-e-c-t- -}- -f-r-o-m- -"-n-e-x-t-/-n-a-v-i-g-a-t-i-o-n-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-s-e-r-v-e-r-"-;-
-
-f-u-n-c-t-i-o-n- -m-o-n-e-y-(-c-e-n-t-s-:- -n-u-m-b-e-r-,- -c-u-r-r-e-n-c-y-:- -s-t-r-i-n-g-)- -{-
- - -r-e-t-u-r-n- -n-e-w- -I-n-t-l-.-N-u-m-b-e-r-F-o-r-m-a-t-(-"-e-n-"-,- -{- -s-t-y-l-e-:- -"-c-u-r-r-e-n-c-y-"-,- -c-u-r-r-e-n-c-y-:- -c-u-r-r-e-n-c-y-.-t-o-U-p-p-e-r-C-a-s-e-(-)- -}-)-.-f-o-r-m-a-t-(-(-c-e-n-t-s- -?-?- -0-)- -/- -1-0-0-)-;-
-}-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -M-y-P-a-y-m-e-n-t-s-P-a-g-e-(-)- -{-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
- - -c-o-n-s-t- -{- -d-a-t-a-:- -u-s-e-r-D-a-t-a- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-a-u-t-h-.-g-e-t-U-s-e-r-(-)-;-
- - -i-f- -(-!-u-s-e-r-D-a-t-a-.-u-s-e-r-)- -r-e-d-i-r-e-c-t-(-"-/-l-o-g-i-n-"-)-;-
-
- - -c-o-n-s-t- -{- -d-a-t-a-:- -p-a-y-m-e-n-t-s- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-p-a-y-m-e-n-t-s-"-)-
- - - - -.-s-e-l-e-c-t-(-"-i-d-,-p-r-o-d-u-c-t-_-t-y-p-e-,-p-r-o-d-u-c-t-_-i-d-,-a-m-o-u-n-t-_-c-e-n-t-s-,-c-u-r-r-e-n-c-y-,-s-t-a-t-u-s-,-c-r-e-a-t-e-d-_-a-t-,-s-t-r-i-p-e-_-c-h-e-c-k-o-u-t-_-s-e-s-s-i-o-n-_-i-d-"-)-
- - - - -.-e-q-(-"-u-s-e-r-_-i-d-"-,- -u-s-e-r-D-a-t-a-.-u-s-e-r-.-i-d-)-
- - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -f-a-l-s-e- -}-)-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-x---a-u-t-o- -m-a-x---w---6-x-l- -p-x---4- -p-y---1-2-"->-
- - - - - - -<-h-1- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---3-x-l- -f-o-n-t---b-o-l-d-"->-I-n-v-o-i-c-e-s- -&- -p-a-y-m-e-n-t-s-<-/-h-1->-
- - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---s-l-a-t-e---6-0-0-"->-Y-o-u-r- -c-h-e-c-k-o-u-t- -a-t-t-e-m-p-t-s- -a-n-d- -c-o-m-p-l-e-t-e-d- -p-u-r-c-h-a-s-e-s-.-<-/-p->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-c-a-r-d- -m-t---8- -o-v-e-r-f-l-o-w---h-i-d-d-e-n-"->-
- - - - - - - - -<-t-a-b-l-e- -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -t-e-x-t---l-e-f-t- -t-e-x-t---s-m-"->-
- - - - - - - - - - -<-t-h-e-a-d- -c-l-a-s-s-N-a-m-e-=-"-b-g---s-l-a-t-e---5-0- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - -<-t-r->-<-t-h- -c-l-a-s-s-N-a-m-e-=-"-p---4-"->-D-a-t-e-<-/-t-h->-<-t-h->-T-y-p-e-<-/-t-h->-<-t-h->-A-m-o-u-n-t-<-/-t-h->-<-t-h->-S-t-a-t-u-s-<-/-t-h->-<-t-h->-S-t-r-i-p-e- -s-e-s-s-i-o-n-<-/-t-h->-<-/-t-r->-
- - - - - - - - - - -<-/-t-h-e-a-d->-
- - - - - - - - - - -<-t-b-o-d-y->-
- - - - - - - - - - - - -{-(-p-a-y-m-e-n-t-s- -?-?- -[-]-)-.-m-a-p-(-(-p-a-y-m-e-n-t-:- -a-n-y-)- -=->- -(-
- - - - - - - - - - - - - - -<-t-r- -k-e-y-=-{-p-a-y-m-e-n-t-.-i-d-}- -c-l-a-s-s-N-a-m-e-=-"-b-o-r-d-e-r---t- -b-o-r-d-e-r---s-l-a-t-e---1-0-0-"->-
- - - - - - - - - - - - - - - - -<-t-d- -c-l-a-s-s-N-a-m-e-=-"-p---4-"->-{-n-e-w- -D-a-t-e-(-p-a-y-m-e-n-t-.-c-r-e-a-t-e-d-_-a-t-)-.-t-o-L-o-c-a-l-e-S-t-r-i-n-g-(-)-}-<-/-t-d->-
- - - - - - - - - - - - - - - - -<-t-d->-{-p-a-y-m-e-n-t-.-p-r-o-d-u-c-t-_-t-y-p-e-}-<-/-t-d->-
- - - - - - - - - - - - - - - - -<-t-d->-{-m-o-n-e-y-(-p-a-y-m-e-n-t-.-a-m-o-u-n-t-_-c-e-n-t-s-,- -p-a-y-m-e-n-t-.-c-u-r-r-e-n-c-y-)-}-<-/-t-d->-
- - - - - - - - - - - - - - - - -<-t-d->-<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-b-a-d-g-e-"->-{-p-a-y-m-e-n-t-.-s-t-a-t-u-s-}-<-/-s-p-a-n->-<-/-t-d->-
- - - - - - - - - - - - - - - - -<-t-d- -c-l-a-s-s-N-a-m-e-=-"-m-a-x---w---x-s- -t-r-u-n-c-a-t-e- -t-e-x-t---s-l-a-t-e---5-0-0-"->-{-p-a-y-m-e-n-t-.-s-t-r-i-p-e-_-c-h-e-c-k-o-u-t-_-s-e-s-s-i-o-n-_-i-d- -?-?- -"---"-}-<-/-t-d->-
- - - - - - - - - - - - - - -<-/-t-r->-
- - - - - - - - - - - - -)-)-}-
- - - - - - - - - - - - -{-(-!-p-a-y-m-e-n-t-s- -|-|- -p-a-y-m-e-n-t-s-.-l-e-n-g-t-h- -=-=-=- -0-)- -?- -(-
- - - - - - - - - - - - - - -<-t-r->-<-t-d- -c-l-a-s-s-N-a-m-e-=-"-p---4- -t-e-x-t---s-l-a-t-e---6-0-0-"- -c-o-l-S-p-a-n-=-{-5-}->-N-o- -p-a-y-m-e-n-t- -r-e-c-o-r-d-s- -y-e-t-.-<-/-t-d->-<-/-t-r->-
- - - - - - - - - - - - -)- -:- -n-u-l-l-}-
- - - - - - - - - - -<-/-t-b-o-d-y->-
- - - - - - - - -<-/-t-a-b-l-e->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-