$ErrorActionPreference = "Stop"

$root = (Get-Location).Path
$path = Join-Path $root "app\admin\documents\receipts\page.tsx"

if (-not (Test-Path -LiteralPath $path)) {
    throw "Cannot find: $path`nRun this script from the LexData project root."
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $root "_backups\fix-receipt-app-profile-embed-$timestamp\app\admin\documents\receipts\page.tsx"

New-Item -ItemType Directory `
    -Path (Split-Path -Parent $backup) `
    -Force |
    Out-Null

Copy-Item `
    -LiteralPath $path `
    -Destination $backup `
    -Force

$content = [System.IO.File]::ReadAllText(
    $path,
    [System.Text.Encoding]::UTF8
)

$changed = $false

# Exact form generated by the current receipt application patch.
$oldExact = '.select("*,workshops(title),profiles(full_name,email)")'
$newExact = '.select("*,workshops(title)")'

if ($content.Contains($oldExact)) {
    $content = $content.Replace(
        $oldExact,
        $newExact
    )
    $changed = $true
    Write-Host "[OK] Removed ambiguous profiles embed from receipt applications query." -ForegroundColor Green
}
else {
    # Flexible recovery for multiline/whitespace variants.
    $pattern = '\.select\(\s*["'']\*,\s*workshops\(title\),\s*profiles\(full_name,\s*email\)["'']\s*\)'

    $regex = [System.Text.RegularExpressions.Regex]::new(
        $pattern,
        [System.Text.RegularExpressions.RegexOptions]::Singleline
    )

    if ($regex.IsMatch($content)) {
        $content = $regex.Replace(
            $content,
            '.select("*,workshops(title)")',
            1
        )
        $changed = $true
        Write-Host "[OK] Removed ambiguous profiles embed using flexible match." -ForegroundColor Green
    }
}

if (-not $changed) {
    if ($content.Contains('profiles!receipt_applications_user_id_fkey')) {
        Write-Host "[OK] Receipt applications query already uses an explicit profiles relationship." -ForegroundColor DarkGreen
    }
    elseif ($content.Contains('.select("*,workshops(title)")')) {
        Write-Host "[OK] Ambiguous profiles embed is already removed." -ForegroundColor DarkGreen
    }
    else {
        throw "Could not locate the receipt_applications select query in the admin receipt page."
    }
}

[System.IO.File]::WriteAllText(
    $path,
    $content,
    $utf8
)

Remove-Item `
    -LiteralPath (Join-Path $root ".next") `
    -Recurse `
    -Force `
    -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Running typecheck..." -ForegroundColor Yellow

npm.cmd run typecheck

if ($LASTEXITCODE -ne 0) {
    Write-Host ""
    Write-Host "[!] TypeScript still reports an error. Paste the exact output." -ForegroundColor Red
    Write-Host "Backup:" -ForegroundColor Yellow
    Write-Host "  $backup"
    exit 1
}

Write-Host ""
Write-Host "[OK] Admin receipt application query fixed." -ForegroundColor Green
Write-Host ""
Write-Host "Backup:" -ForegroundColor Cyan
Write-Host "  $backup"
Write-Host ""
Write-Host "Restart dev server if it is already running:" -ForegroundColor Yellow
Write-Host "  npm.cmd run dev"
