-i-m-p-o-r-t- -L-i-n-k- -f-r-o-m- -"-n-e-x-t-/-l-i-n-k-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-a-d-m-i-n-"-;-
-i-m-p-o-r-t- -T-e-a-m-M-e-d-i-a- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-T-e-a-m-M-e-d-i-a-"-;-
-
-e-x-p-o-r-t- -c-o-n-s-t- -d-y-n-a-m-i-c- -=- -"-f-o-r-c-e---d-y-n-a-m-i-c-"-;-
-e-x-p-o-r-t- -c-o-n-s-t- -r-e-v-a-l-i-d-a-t-e- -=- -0-;-
-
-t-y-p-e- -T-e-a-m-M-e-m-b-e-r- -=- -{-
- - -i-d-:- -s-t-r-i-n-g-;-
- - -n-a-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -f-u-l-l-_-n-a-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -r-o-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -r-o-l-e-_-t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-o-s-i-t-i-o-n-_-t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-e-c-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -i-n-s-t-i-t-u-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -o-r-g-a-n-i-z-a-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -b-i-o-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-h-o-t-o-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-r-o-f-i-l-e-_-i-m-a-g-e-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-t-y-p-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -v-i-d-e-o-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-t-y-l-e-_-p-r-e-s-e-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -i-n-i-t-i-a-l-s-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-r-o-f-i-l-e-_-s-l-u-g-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-r-o-f-i-l-e-_-h-i-g-h-l-i-g-h-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-r-o-f-i-l-e-_-c-t-a-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -e-m-a-i-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -l-i-n-k-e-d-i-n-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -w-e-b-s-i-t-e-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-i-s-p-l-a-y-_-o-r-d-e-r-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -s-o-r-t-_-o-r-d-e-r-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -i-s-_-a-c-t-i-v-e-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -i-s-_-p-u-b-l-i-s-h-e-d-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
-}-;-
-
-f-u-n-c-t-i-o-n- -g-e-t-N-a-m-e-(-m-e-m-b-e-r-:- -T-e-a-m-M-e-m-b-e-r-)- -{-
- - -r-e-t-u-r-n- -m-e-m-b-e-r-.-f-u-l-l-_-n-a-m-e- -|-|- -m-e-m-b-e-r-.-n-a-m-e- -|-|- -"-U-n-n-a-m-e-d- -m-e-m-b-e-r-"-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-R-o-l-e-(-m-e-m-b-e-r-:- -T-e-a-m-M-e-m-b-e-r-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -m-e-m-b-e-r-.-p-o-s-i-t-i-o-n-_-t-i-t-l-e- -|-|-
- - - - -m-e-m-b-e-r-.-r-o-l-e-_-t-i-t-l-e- -|-|-
- - - - -m-e-m-b-e-r-.-r-o-l-e- -|-|-
- - - - -m-e-m-b-e-r-.-t-i-t-l-e- -|-|-
- - - - -"-T-e-a-m- -M-e-m-b-e-r-"-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-M-e-d-i-a-U-r-l-(-m-e-m-b-e-r-:- -T-e-a-m-M-e-m-b-e-r-)- -{-
- - -r-e-t-u-r-n- -m-e-m-b-e-r-.-m-e-d-i-a-_-u-r-l- -|-|- -m-e-m-b-e-r-.-p-h-o-t-o-_-u-r-l- -|-|- -m-e-m-b-e-r-.-p-r-o-f-i-l-e-_-i-m-a-g-e-_-u-r-l- -|-|- -n-u-l-l-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-P-r-o-f-i-l-e-U-r-l-(-m-e-m-b-e-r-:- -T-e-a-m-M-e-m-b-e-r-)- -{-
- - -r-e-t-u-r-n- -m-e-m-b-e-r-.-p-r-o-f-i-l-e-_-s-l-u-g- -?- -`-/-t-e-a-m-/-$-{-m-e-m-b-e-r-.-p-r-o-f-i-l-e-_-s-l-u-g-}-`- -:- -`-/-t-e-a-m-/-$-{-m-e-m-b-e-r-.-i-d-}-`-;-
-}-
-
-f-u-n-c-t-i-o-n- -i-s-V-i-s-i-b-l-e-(-m-e-m-b-e-r-:- -T-e-a-m-M-e-m-b-e-r-)- -{-
- - -i-f- -(-m-e-m-b-e-r-.-i-s-_-a-c-t-i-v-e- -=-=-=- -f-a-l-s-e-)- -r-e-t-u-r-n- -f-a-l-s-e-;-
- - -i-f- -(-m-e-m-b-e-r-.-i-s-_-p-u-b-l-i-s-h-e-d- -=-=-=- -f-a-l-s-e-)- -r-e-t-u-r-n- -f-a-l-s-e-;-
- - -r-e-t-u-r-n- -t-r-u-e-;-
-}-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -T-e-a-m-P-a-g-e-(-)- -{-
- - -c-o-n-s-t- -a-d-m-i-n- -=- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -{- -d-a-t-a-,- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -a-d-m-i-n-
- - - - -.-f-r-o-m-(-"-t-e-a-m-_-m-e-m-b-e-r-s-"-)-
- - - - -.-s-e-l-e-c-t-(-"-*-"-)-
- - - - -.-o-r-d-e-r-(-"-s-o-r-t-_-o-r-d-e-r-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-
- - - - -.-o-r-d-e-r-(-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-
- - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -f-a-l-s-e- -}-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -t-h-r-o-w- -n-e-w- -E-r-r-o-r-(-`-C-o-u-l-d- -n-o-t- -l-o-a-d- -t-e-a-m- -m-e-m-b-e-r-s-:- -$-{-e-r-r-o-r-.-m-e-s-s-a-g-e-}-`-)-;-
- - -}-
-
- - -c-o-n-s-t- -m-e-m-b-e-r-s- -=- -(-(-d-a-t-a- -?-?- -[-]-)- -a-s- -T-e-a-m-M-e-m-b-e-r-[-]-)-.-f-i-l-t-e-r-(-i-s-V-i-s-i-b-l-e-)-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-m-a-i-n- -c-l-a-s-s-N-a-m-e-=-"-m-x---a-u-t-o- -m-a-x---w---7-x-l- -p-x---4- -p-y---1-2-"->-
- - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-b---1-0- -r-o-u-n-d-e-d---[-2-r-e-m-]- -b-g---s-l-a-t-e---9-5-0- -p---8- -t-e-x-t---w-h-i-t-e-"->-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---s-m- -f-o-n-t---b-l-a-c-k- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-2-5-e-m-]- -t-e-x-t---b-l-u-e---3-0-0-"->-
- - - - - - - - - - -O-u-r- -T-e-a-m-
- - - - - - - - -<-/-p->-
-
- - - - - - - - -<-h-1- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---4-x-l- -f-o-n-t---b-l-a-c-k- -t-r-a-c-k-i-n-g---t-i-g-h-t- -m-d-:-t-e-x-t---5-x-l-"->-
- - - - - - - - - - -M-e-e-t- -t-h-e- -L-e-x-D-a-t-a- -t-e-a-m-
- - - - - - - - -<-/-h-1->-
-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -m-a-x---w---3-x-l- -t-e-x-t---s-l-a-t-e---3-0-0-"->-
- - - - - - - - - - -R-e-s-e-a-r-c-h-e-r-s-,- -t-r-a-i-n-e-r-s-,- -m-a-n-a-g-e-r-s-,- -a-d-v-i-s-o-r-s-,- -a-n-d- -c-o-l-l-a-b-o-r-a-t-o-r-s-
- - - - - - - - - - -s-u-p-p-o-r-t-i-n-g- -L-e-x-D-a-t-a- -w-o-r-k-s-h-o-p-s- -a-n-d- -r-e-s-e-a-r-c-h- -t-r-a-i-n-i-n-g-.-
- - - - - - - - -<-/-p->-
- - - - - - -<-/-s-e-c-t-i-o-n->-
-
- - - - - - -{-m-e-m-b-e-r-s-.-l-e-n-g-t-h- -=-=-=- -0- -?- -(-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---8- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - -T-e-a-m- -i-n-f-o-r-m-a-t-i-o-n- -w-i-l-l- -b-e- -p-u-b-l-i-s-h-e-d- -s-o-o-n-.-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -)- -:- -(-
- - - - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---6- -m-d-:-g-r-i-d---c-o-l-s---2- -l-g-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - -{-m-e-m-b-e-r-s-.-m-a-p-(-(-m-e-m-b-e-r-)- -=->- -{-
- - - - - - - - - - - - -c-o-n-s-t- -n-a-m-e- -=- -g-e-t-N-a-m-e-(-m-e-m-b-e-r-)-;-
- - - - - - - - - - - - -c-o-n-s-t- -r-o-l-e- -=- -g-e-t-R-o-l-e-(-m-e-m-b-e-r-)-;-
- - - - - - - - - - - - -c-o-n-s-t- -p-r-o-f-i-l-e-U-r-l- -=- -g-e-t-P-r-o-f-i-l-e-U-r-l-(-m-e-m-b-e-r-)-;-
-
- - - - - - - - - - - - -r-e-t-u-r-n- -(-
- - - - - - - - - - - - - - -<-L-i-n-k-
- - - - - - - - - - - - - - - - -k-e-y-=-{-m-e-m-b-e-r-.-i-d-}-
- - - - - - - - - - - - - - - - -h-r-e-f-=-{-p-r-o-f-i-l-e-U-r-l-}-
- - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-g-r-o-u-p- -o-v-e-r-f-l-o-w---h-i-d-d-e-n- -r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -s-h-a-d-o-w---s-m- -t-r-a-n-s-i-t-i-o-n- -h-o-v-e-r-:---t-r-a-n-s-l-a-t-e---y---1- -h-o-v-e-r-:-s-h-a-d-o-w---x-l-"-
- - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - -<-T-e-a-m-M-e-d-i-a-
- - - - - - - - - - - - - - - - - - -n-a-m-e-=-{-n-a-m-e-}-
- - - - - - - - - - - - - - - - - - -i-n-i-t-i-a-l-s-=-{-m-e-m-b-e-r-.-i-n-i-t-i-a-l-s-}-
- - - - - - - - - - - - - - - - - - -m-e-d-i-a-T-y-p-e-=-{-m-e-m-b-e-r-.-m-e-d-i-a-_-t-y-p-e-}-
- - - - - - - - - - - - - - - - - - -m-e-d-i-a-U-r-l-=-{-g-e-t-M-e-d-i-a-U-r-l-(-m-e-m-b-e-r-)-}-
- - - - - - - - - - - - - - - - - - -v-i-d-e-o-U-r-l-=-{-m-e-m-b-e-r-.-v-i-d-e-o-_-u-r-l-}-
- - - - - - - - - - - - - - - - - - -s-t-y-l-e-P-r-e-s-e-t-=-{-m-e-m-b-e-r-.-s-t-y-l-e-_-p-r-e-s-e-t-}-
- - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p---6-"->-
- - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---x-s- -f-o-n-t---s-e-m-i-b-o-l-d- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-1-8-e-m-]- -t-e-x-t---s-l-a-t-e---4-0-0-"->-
- - - - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-s-e-c-t-i-o-n- -|-|- -"-T-e-a-m-"-}-
- - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0- -g-r-o-u-p---h-o-v-e-r-:-t-e-x-t---b-l-u-e---7-0-0-"->-
- - - - - - - - - - - - - - - - - - - - -{-n-a-m-e-}-
- - - - - - - - - - - - - - - - - - -<-/-h-2->-
-
- - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---1- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---b-l-u-e---7-0-0-"->-
- - - - - - - - - - - - - - - - - - - - -{-r-o-l-e-}-
- - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-i-n-s-t-i-t-u-t-i-o-n- -|-|- -m-e-m-b-e-r-.-o-r-g-a-n-i-z-a-t-i-o-n- -?- -(-
- - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---5-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-i-n-s-t-i-t-u-t-i-o-n- -|-|- -m-e-m-b-e-r-.-o-r-g-a-n-i-z-a-t-i-o-n-}-
- - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-b-i-o- -?- -(-
- - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -l-i-n-e---c-l-a-m-p---4- -t-e-x-t---s-m- -l-e-a-d-i-n-g---6- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-b-i-o-}-
- - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-m-t---5- -i-n-l-i-n-e---f-l-e-x- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---3-0-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---s-e-m-i-b-o-l-d- -t-e-x-t---s-l-a-t-e---7-0-0- -g-r-o-u-p---h-o-v-e-r-:-b-g---s-l-a-t-e---1-0-0-"->-
- - - - - - - - - - - - - - - - - - - - -{-m-e-m-b-e-r-.-p-r-o-f-i-l-e-_-c-t-a- -|-|- -"-V-i-e-w- -P-r-o-f-i-l-e-"-}-
- - - - - - - - - - - - - - - - - - -<-/-s-p-a-n->-
- - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - - - - - -)-;-
- - - - - - - - - - -}-)-}-
- - - - - - - - -<-/-s-e-c-t-i-o-n->-
- - - - - - -)-}-
- - - - -<-/-m-a-i-n->-
- - -)-;-
-}-