-i-m-p-o-r-t- -L-i-n-k- -f-r-o-m- -"-n-e-x-t-/-l-i-n-k-"-;-
-i-m-p-o-r-t- -{- -u-n-s-t-a-b-l-e-_-n-o-S-t-o-r-e- -a-s- -n-o-S-t-o-r-e- -}- -f-r-o-m- -"-n-e-x-t-/-c-a-c-h-e-"-;-
-i-m-p-o-r-t- -{- -r-e-q-u-i-r-e-A-d-m-i-n- -}- -f-r-o-m- -"-@-/-l-i-b-/-a-u-t-h-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-a-d-m-i-n-"-;-
-i-m-p-o-r-t- -{-
- - -c-r-e-a-t-e-W-o-r-k-s-h-o-p-,-
- - -c-r-e-a-t-e-W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-,-
- - -c-r-e-a-t-e-W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-,-
- - -d-e-l-e-t-e-W-o-r-k-s-h-o-p-,-
- - -d-e-l-e-t-e-W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-,-
- - -d-e-l-e-t-e-W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-,-
-}- -f-r-o-m- -"-.-/-a-c-t-i-o-n-s-"-;-
-i-m-p-o-r-t- -S-e-s-s-i-o-n-M-e-d-i-a-U-p-l-o-a-d-e-r- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-S-e-s-s-i-o-n-M-e-d-i-a-U-p-l-o-a-d-e-r-"-;-
-
-e-x-p-o-r-t- -c-o-n-s-t- -d-y-n-a-m-i-c- -=- -"-f-o-r-c-e---d-y-n-a-m-i-c-"-;-
-e-x-p-o-r-t- -c-o-n-s-t- -r-e-v-a-l-i-d-a-t-e- -=- -0-;-
-
-t-y-p-e- -W-o-r-k-s-h-o-p- -=- -{-
- - -i-d-:- -s-t-r-i-n-g-;-
- - -t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-l-u-g-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-u-m-m-a-r-y-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-e-s-c-r-i-p-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -i-n-s-t-r-u-c-t-o-r-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-p-e-a-k-e-r-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -l-e-v-e-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -l-a-n-g-u-a-g-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -f-o-r-m-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -l-o-c-a-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-t-a-r-t-_-d-a-t-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-a-t-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -e-n-d-_-d-a-t-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-u-r-a-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -p-r-i-c-e-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -c-u-r-r-e-n-c-y-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -c-a-p-a-c-i-t-y-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -i-m-a-g-e-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -c-o-v-e-r-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -t-h-u-m-b-n-a-i-l-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-a-t-e-r-i-a-l-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-a-t-e-r-i-a-l-s-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -r-e-s-o-u-r-c-e-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -f-i-l-e-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -i-s-_-f-e-a-t-u-r-e-d-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -i-s-_-p-u-b-l-i-s-h-e-d-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -i-s-_-a-c-t-i-v-e-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -c-r-e-a-t-e-d-_-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
-}-;-
-
-t-y-p-e- -W-o-r-k-s-h-o-p-S-e-s-s-i-o-n- -=- -{-
- - -i-d-:- -s-t-r-i-n-g-;-
- - -w-o-r-k-s-h-o-p-_-i-d-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-e-s-s-i-o-n-_-d-a-t-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-t-a-r-t-_-t-i-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -e-n-d-_-t-i-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-t-a-r-t-s-_-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -e-n-d-s-_-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -l-o-c-a-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-e-t-i-n-g-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -r-e-c-o-r-d-i-n-g-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-a-t-e-r-i-a-l-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-t-y-p-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-i-s-p-l-a-y-_-o-r-d-e-r-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -i-s-_-a-c-t-i-v-e-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -c-r-e-a-t-e-d-_-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
-}-;-
-
-t-y-p-e- -W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n- -=- -{-
- - -i-d-:- -s-t-r-i-n-g-;-
- - -s-e-s-s-i-o-n-_-i-d-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -t-i-t-l-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-e-s-c-r-i-p-t-i-o-n-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -s-t-a-r-t-_-t-i-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -e-n-d-_-t-i-m-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-e-t-i-n-g-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -r-e-c-o-r-d-i-n-g-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-a-t-e-r-i-a-l-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-t-y-p-e-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -m-e-d-i-a-_-u-r-l-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
- - -d-i-s-p-l-a-y-_-o-r-d-e-r-?-:- -n-u-m-b-e-r- -|- -n-u-l-l-;-
- - -i-s-_-a-c-t-i-v-e-?-:- -b-o-o-l-e-a-n- -|- -n-u-l-l-;-
- - -c-r-e-a-t-e-d-_-a-t-?-:- -s-t-r-i-n-g- -|- -n-u-l-l-;-
-}-;-
-
-f-u-n-c-t-i-o-n- -g-e-t-W-o-r-k-s-h-o-p-D-e-s-c-r-i-p-t-i-o-n-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -r-e-t-u-r-n- -w-o-r-k-s-h-o-p-.-s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n- -|-|- -w-o-r-k-s-h-o-p-.-s-u-m-m-a-r-y- -|-|- -w-o-r-k-s-h-o-p-.-d-e-s-c-r-i-p-t-i-o-n- -|-|- -"-"-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-W-o-r-k-s-h-o-p-D-a-t-e-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -r-e-t-u-r-n- -w-o-r-k-s-h-o-p-.-s-t-a-r-t-_-d-a-t-e- -|-|- -w-o-r-k-s-h-o-p-.-d-a-t-e- -|-|- -"-"-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-W-o-r-k-s-h-o-p-S-p-e-a-k-e-r-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -r-e-t-u-r-n- -w-o-r-k-s-h-o-p-.-i-n-s-t-r-u-c-t-o-r- -|-|- -w-o-r-k-s-h-o-p-.-s-p-e-a-k-e-r- -|-|- -"-"-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-W-o-r-k-s-h-o-p-I-m-a-g-e-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -r-e-t-u-r-n- -w-o-r-k-s-h-o-p-.-i-m-a-g-e-_-u-r-l- -|-|- -w-o-r-k-s-h-o-p-.-c-o-v-e-r-_-u-r-l- -|-|- -w-o-r-k-s-h-o-p-.-t-h-u-m-b-n-a-i-l-_-u-r-l- -|-|- -"-"-;-
-}-
-
-f-u-n-c-t-i-o-n- -g-e-t-W-o-r-k-s-h-o-p-M-a-t-e-r-i-a-l-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -w-o-r-k-s-h-o-p-.-m-a-t-e-r-i-a-l-_-u-r-l- -|-|-
- - - - -w-o-r-k-s-h-o-p-.-m-a-t-e-r-i-a-l-s-_-u-r-l- -|-|-
- - - - -w-o-r-k-s-h-o-p-.-r-e-s-o-u-r-c-e-_-u-r-l- -|-|-
- - - - -w-o-r-k-s-h-o-p-.-f-i-l-e-_-u-r-l- -|-|-
- - - - -"-"-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -f-o-r-m-a-t-P-r-i-c-e-(-w-o-r-k-s-h-o-p-:- -W-o-r-k-s-h-o-p-)- -{-
- - -c-o-n-s-t- -p-r-i-c-e- -=- -w-o-r-k-s-h-o-p-.-p-r-i-c-e- -?-?- -0-;-
- - -c-o-n-s-t- -c-u-r-r-e-n-c-y- -=- -w-o-r-k-s-h-o-p-.-c-u-r-r-e-n-c-y- -|-|- -"-U-S-D-"-;-
-
- - -i-f- -(-!-p-r-i-c-e-)- -{-
- - - - -r-e-t-u-r-n- -"-F-r-e-e- -/- -N-o-t- -s-e-t-"-;-
- - -}-
-
- - -r-e-t-u-r-n- -`-$-{-c-u-r-r-e-n-c-y-}- -$-{-p-r-i-c-e-}-`-;-
-}-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -A-d-m-i-n-W-o-r-k-s-h-o-p-s-P-a-g-e-(-{-
- - -s-e-a-r-c-h-P-a-r-a-m-s-,-
-}-:- -{-
- - -s-e-a-r-c-h-P-a-r-a-m-s-:- -P-r-o-m-i-s-e-<-{- -m-e-s-s-a-g-e-?-:- -s-t-r-i-n-g- -}->-;-
-}-)- -{-
- - -n-o-S-t-o-r-e-(-)-;-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
-
- - -c-o-n-s-t- -{- -m-e-s-s-a-g-e- -}- -=- -a-w-a-i-t- -s-e-a-r-c-h-P-a-r-a-m-s-;-
-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -{- -d-a-t-a-:- -w-o-r-k-s-h-o-p-s-D-a-t-a-,- -e-r-r-o-r-:- -w-o-r-k-s-h-o-p-s-E-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-w-o-r-k-s-h-o-p-s-"-)-
- - - - -.-s-e-l-e-c-t-(-"-*-"-)-
- - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -f-a-l-s-e- -}-)-;-
-
- - -c-o-n-s-t- -{- -d-a-t-a-:- -s-e-s-s-i-o-n-s-D-a-t-a-,- -e-r-r-o-r-:- -s-e-s-s-i-o-n-s-E-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-w-o-r-k-s-h-o-p-_-s-e-s-s-i-o-n-s-"-)-
- - - - -.-s-e-l-e-c-t-(-"-*-"-)-
- - - - -.-o-r-d-e-r-(-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-
- - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-;-
-
- - -c-o-n-s-t- -{- -d-a-t-a-:- -s-u-b-s-e-s-s-i-o-n-s-D-a-t-a-,- -e-r-r-o-r-:- -s-u-b-s-e-s-s-i-o-n-s-E-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-w-o-r-k-s-h-o-p-_-s-u-b-s-e-s-s-i-o-n-s-"-)-
- - - - -.-s-e-l-e-c-t-(-"-*-"-)-
- - - - -.-o-r-d-e-r-(-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-
- - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-;-
-
- - -c-o-n-s-t- -w-o-r-k-s-h-o-p-s- -=- -(-w-o-r-k-s-h-o-p-s-D-a-t-a- -?-?- -[-]-)- -a-s- -W-o-r-k-s-h-o-p-[-]-;-
- - -c-o-n-s-t- -s-e-s-s-i-o-n-s- -=- -(-s-e-s-s-i-o-n-s-D-a-t-a- -?-?- -[-]-)- -a-s- -W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-[-]-;-
- - -c-o-n-s-t- -s-u-b-s-e-s-s-i-o-n-s- -=- -(-s-u-b-s-e-s-s-i-o-n-s-D-a-t-a- -?-?- -[-]-)- -a-s- -W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-[-]-;-
-
- - -c-o-n-s-t- -w-o-r-k-s-h-o-p-B-y-I-d- -=- -n-e-w- -M-a-p-(-
- - - - -w-o-r-k-s-h-o-p-s-.-m-a-p-(-(-w-o-r-k-s-h-o-p-)- -=->- -[-w-o-r-k-s-h-o-p-.-i-d-,- -w-o-r-k-s-h-o-p-]-)-
- - -)-;-
-
- - -c-o-n-s-t- -s-e-s-s-i-o-n-s-B-y-W-o-r-k-s-h-o-p-I-d- -=- -n-e-w- -M-a-p-<-s-t-r-i-n-g-,- -W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-[-]->-(-)-;-
-
- - -f-o-r- -(-c-o-n-s-t- -s-e-s-s-i-o-n- -o-f- -s-e-s-s-i-o-n-s-)- -{-
- - - - -i-f- -(-!-s-e-s-s-i-o-n-.-w-o-r-k-s-h-o-p-_-i-d-)- -c-o-n-t-i-n-u-e-;-
-
- - - - -c-o-n-s-t- -e-x-i-s-t-i-n-g- -=- -s-e-s-s-i-o-n-s-B-y-W-o-r-k-s-h-o-p-I-d-.-g-e-t-(-s-e-s-s-i-o-n-.-w-o-r-k-s-h-o-p-_-i-d-)- -?-?- -[-]-;-
- - - - -e-x-i-s-t-i-n-g-.-p-u-s-h-(-s-e-s-s-i-o-n-)-;-
- - - - -s-e-s-s-i-o-n-s-B-y-W-o-r-k-s-h-o-p-I-d-.-s-e-t-(-s-e-s-s-i-o-n-.-w-o-r-k-s-h-o-p-_-i-d-,- -e-x-i-s-t-i-n-g-)-;-
- - -}-
-
- - -c-o-n-s-t- -s-u-b-s-e-s-s-i-o-n-s-B-y-S-e-s-s-i-o-n-I-d- -=- -n-e-w- -M-a-p-<-s-t-r-i-n-g-,- -W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-[-]->-(-)-;-
-
- - -f-o-r- -(-c-o-n-s-t- -s-u-b-s-e-s-s-i-o-n- -o-f- -s-u-b-s-e-s-s-i-o-n-s-)- -{-
- - - - -i-f- -(-!-s-u-b-s-e-s-s-i-o-n-.-s-e-s-s-i-o-n-_-i-d-)- -c-o-n-t-i-n-u-e-;-
-
- - - - -c-o-n-s-t- -e-x-i-s-t-i-n-g- -=- -s-u-b-s-e-s-s-i-o-n-s-B-y-S-e-s-s-i-o-n-I-d-.-g-e-t-(-s-u-b-s-e-s-s-i-o-n-.-s-e-s-s-i-o-n-_-i-d-)- -?-?- -[-]-;-
- - - - -e-x-i-s-t-i-n-g-.-p-u-s-h-(-s-u-b-s-e-s-s-i-o-n-)-;-
- - - - -s-u-b-s-e-s-s-i-o-n-s-B-y-S-e-s-s-i-o-n-I-d-.-s-e-t-(-s-u-b-s-e-s-s-i-o-n-.-s-e-s-s-i-o-n-_-i-d-,- -e-x-i-s-t-i-n-g-)-;-
- - -}-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-m-a-i-n- -c-l-a-s-s-N-a-m-e-=-"-m-x---a-u-t-o- -m-a-x---w---7-x-l- -p-x---4- -p-y---1-0-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-b---1-0-"->-
- - - - - - - - -<-L-i-n-k-
- - - - - - - - - - -h-r-e-f-=-"-/-a-d-m-i-n-"-
- - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---s-m- -f-o-n-t---s-e-m-i-b-o-l-d- -t-e-x-t---s-l-a-t-e---6-0-0- -h-o-v-e-r-:-t-e-x-t---s-l-a-t-e---9-5-0-"-
- - - - - - - - ->-
- - - - - - - - - - ---&-g-t-;-B-a-c-k- -t-o- -a-d-m-i-n- -d-a-s-h-b-o-a-r-d-
- - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -t-e-x-t---s-m- -f-o-n-t---s-e-m-i-b-o-l-d- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-2-5-e-m-]- -t-e-x-t---s-l-a-t-e---5-0-0-"->-
- - - - - - - - - - -A-d-m-i-n- -D-a-s-h-b-o-a-r-d-
- - - - - - - - -<-/-p->-
-
- - - - - - - - -<-h-1- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---4-x-l- -f-o-n-t---b-l-a-c-k- -t-r-a-c-k-i-n-g---t-i-g-h-t- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - -W-o-r-k-s-h-o-p-s-
- - - - - - - - -<-/-h-1->-
-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -m-a-x---w---3-x-l- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - -C-r-e-a-t-e- -w-o-r-k-s-h-o-p-s-,- -a-d-d- -m-a-j-o-r- -s-e-s-s-i-o-n-s-,- -a-d-d- -s-u-b-s-e-s-s-i-o-n-s-,- -e-d-i-t-
- - - - - - - - - - -s-u-b-s-e-s-s-i-o-n-s-,- -a-n-d- -m-a-n-a-g-e- -w-o-r-k-s-h-o-p- -v-i-s-i-b-i-l-i-t-y-.-
- - - - - - - - -<-/-p->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -{-m-e-s-s-a-g-e- -?- -(-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-b---6- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---s-l-a-t-e---5-0- -p-x---4- -p-y---3- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---7-0-0-"->-
- - - - - - - - - - -{-m-e-s-s-a-g-e-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - -{-w-o-r-k-s-h-o-p-s-E-r-r-o-r- -?- -(-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-b---6- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -b-g---r-e-d---5-0- -p-x---4- -p-y---3- -t-e-x-t---s-m- -t-e-x-t---r-e-d---7-0-0-"->-
- - - - - - - - - - -W-o-r-k-s-h-o-p-s- -e-r-r-o-r-:- -{-w-o-r-k-s-h-o-p-s-E-r-r-o-r-.-m-e-s-s-a-g-e-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - -{-s-e-s-s-i-o-n-s-E-r-r-o-r- -?- -(-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-b---6- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -b-g---r-e-d---5-0- -p-x---4- -p-y---3- -t-e-x-t---s-m- -t-e-x-t---r-e-d---7-0-0-"->-
- - - - - - - - - - -S-e-s-s-i-o-n-s- -e-r-r-o-r-:- -{-s-e-s-s-i-o-n-s-E-r-r-o-r-.-m-e-s-s-a-g-e-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - -{-s-u-b-s-e-s-s-i-o-n-s-E-r-r-o-r- -?- -(-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-b---6- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -b-g---r-e-d---5-0- -p-x---4- -p-y---3- -t-e-x-t---s-m- -t-e-x-t---r-e-d---7-0-0-"->-
- - - - - - - - - - -S-u-b-s-e-s-s-i-o-n-s- -e-r-r-o-r-:- -{-s-u-b-s-e-s-s-i-o-n-s-E-r-r-o-r-.-m-e-s-s-a-g-e-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-b---1-0- -r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---6- -s-h-a-d-o-w---s-m-"->-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - -A-d-d- -N-e-w- -W-o-r-k-s-h-o-p-
- - - - - - - - -<-/-h-2->-
-
- - - - - - - - -<-f-o-r-m- -a-c-t-i-o-n-=-{-c-r-e-a-t-e-W-o-r-k-s-h-o-p-}- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -g-r-i-d- -g-a-p---5-"->-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---2-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-t-i-t-l-e-"-
- - - - - - - - - - - - - - -r-e-q-u-i-r-e-d-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-W-o-r-k-s-h-o-p- -t-i-t-l-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-s-l-u-g-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-w-o-r-k-s-h-o-p---u-r-l---s-l-u-g-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-t-e-x-t-a-r-e-a-
- - - - - - - - - - - - -n-a-m-e-=-"-s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-"-
- - - - - - - - - - - - -r-o-w-s-=-{-3-}-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-S-h-o-r-t- -d-e-s-c-r-i-p-t-i-o-n-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-t-e-x-t-a-r-e-a-
- - - - - - - - - - - - -n-a-m-e-=-"-d-e-s-c-r-i-p-t-i-o-n-"-
- - - - - - - - - - - - -r-o-w-s-=-{-5-}-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-F-u-l-l- -w-o-r-k-s-h-o-p- -i-n-t-r-o-d-u-c-t-i-o-n-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-i-n-s-t-r-u-c-t-o-r-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-I-n-s-t-r-u-c-t-o-r- -/- -S-p-e-a-k-e-r-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-l-e-v-e-l-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-"-B-e-g-i-n-n-e-r-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-L-e-v-e-l-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-l-a-n-g-u-a-g-e-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-"-E-n-g-l-i-s-h-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-L-a-n-g-u-a-g-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-f-o-r-m-a-t-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-"-O-n-l-i-n-e-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-O-n-l-i-n-e- -/- -O-f-f-l-i-n-e- -/- -H-y-b-r-i-d-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-l-o-c-a-t-i-o-n-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-L-o-c-a-t-i-o-n-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-d-u-r-a-t-i-o-n-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-D-u-r-a-t-i-o-n-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-s-t-a-r-t-_-d-a-t-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-d-a-t-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-e-n-d-_-d-a-t-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-d-a-t-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-c-a-p-a-c-i-t-y-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-n-u-m-b-e-r-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-{-0-}-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-C-a-p-a-c-i-t-y-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-p-r-i-c-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-n-u-m-b-e-r-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-{-0-}-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-P-r-i-c-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-c-u-r-r-e-n-c-y-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-"-U-S-D-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-C-u-r-r-e-n-c-y-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-i-m-a-g-e-_-u-r-l-"-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-C-o-v-e-r- -i-m-a-g-e- -U-R-L-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-m-a-t-e-r-i-a-l-_-u-r-l-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-W-o-r-k-s-h-o-p- -m-a-t-e-r-i-a-l- -U-R-L-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -f-l-e-x---w-r-a-p- -g-a-p---6-"->-
- - - - - - - - - - - - -<-l-a-b-e-l- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -i-t-e-m-s---c-e-n-t-e-r- -g-a-p---2-"->-
- - - - - - - - - - - - - - -<-i-n-p-u-t- -n-a-m-e-=-"-i-s-_-f-e-a-t-u-r-e-d-"- -t-y-p-e-=-"-c-h-e-c-k-b-o-x-"- -/->-
- - - - - - - - - - - - - - -<-s-p-a-n->-F-e-a-t-u-r-e-d- -w-o-r-k-s-h-o-p-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-/-l-a-b-e-l->-
-
- - - - - - - - - - - - -<-l-a-b-e-l- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -i-t-e-m-s---c-e-n-t-e-r- -g-a-p---2-"->-
- - - - - - - - - - - - - - -<-i-n-p-u-t- -n-a-m-e-=-"-i-s-_-p-u-b-l-i-s-h-e-d-"- -t-y-p-e-=-"-c-h-e-c-k-b-o-x-"- -d-e-f-a-u-l-t-C-h-e-c-k-e-d- -/->-
- - - - - - - - - - - - - - -<-s-p-a-n->-P-u-b-l-i-s-h-e-d-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-/-l-a-b-e-l->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-i-t- -r-o-u-n-d-e-d---x-l- -b-g---s-l-a-t-e---9-5-0- -p-x---5- -p-y---3- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---w-h-i-t-e- -h-o-v-e-r-:-b-g---s-l-a-t-e---7-0-0-"-
- - - - - - - - - - ->-
- - - - - - - - - - - - -C-r-e-a-t-e- -W-o-r-k-s-h-o-p-
- - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - -<-/-f-o-r-m->-
- - - - - - -<-/-s-e-c-t-i-o-n->-
-
- - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-b---1-0- -r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---6- -s-h-a-d-o-w---s-m-"->-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - -A-d-d- -M-a-j-o-r- -S-e-s-s-i-o-n-
- - - - - - - - -<-/-h-2->-
-
- - - - - - - - -<-f-o-r-m- -a-c-t-i-o-n-=-{-c-r-e-a-t-e-W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-}- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -g-r-i-d- -g-a-p---5-"->-
- - - - - - - - - - -<-s-e-l-e-c-t-
- - - - - - - - - - - - -n-a-m-e-=-"-w-o-r-k-s-h-o-p-_-i-d-"-
- - - - - - - - - - - - -r-e-q-u-i-r-e-d-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - ->-
- - - - - - - - - - - - -<-o-p-t-i-o-n- -v-a-l-u-e-=-"-"->-C-h-o-o-s-e- -w-o-r-k-s-h-o-p-<-/-o-p-t-i-o-n->-
- - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-s-.-m-a-p-(-(-w-o-r-k-s-h-o-p-)- -=->- -(-
- - - - - - - - - - - - - - -<-o-p-t-i-o-n- -k-e-y-=-{-w-o-r-k-s-h-o-p-.-i-d-}- -v-a-l-u-e-=-{-w-o-r-k-s-h-o-p-.-i-d-}->-
- - - - - - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-.-t-i-t-l-e-}-
- - - - - - - - - - - - - - -<-/-o-p-t-i-o-n->-
- - - - - - - - - - - - -)-)-}-
- - - - - - - - - - -<-/-s-e-l-e-c-t->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---2-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-t-i-t-l-e-"-
- - - - - - - - - - - - - - -r-e-q-u-i-r-e-d-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-M-a-j-o-r- -s-e-s-s-i-o-n- -t-i-t-l-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-n-u-m-b-e-r-"-
- - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-{-0-}-
- - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-D-i-s-p-l-a-y- -o-r-d-e-r-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---5- -m-d-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-s-e-s-s-i-o-n-_-d-a-t-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-d-a-t-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-s-t-a-r-t-_-t-i-m-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-t-i-m-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - -n-a-m-e-=-"-e-n-d-_-t-i-m-e-"-
- - - - - - - - - - - - - - -t-y-p-e-=-"-t-i-m-e-"-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - -/->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-l-o-c-a-t-i-o-n-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-L-o-c-a-t-i-o-n-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-m-e-e-t-i-n-g-_-u-r-l-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-M-e-e-t-i-n-g- -/- -Z-o-o-m- -U-R-L-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-r-e-c-o-r-d-i-n-g-_-u-r-l-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-R-e-c-o-r-d-i-n-g- -U-R-L-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-m-a-t-e-r-i-a-l-_-u-r-l-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-M-a-t-e-r-i-a-l- -U-R-L-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-S-e-s-s-i-o-n-M-e-d-i-a-U-p-l-o-a-d-e-r- -/->-
-
- - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - -n-a-m-e-=-"-e-x-t-e-r-n-a-l-_-v-i-d-e-o-_-u-r-l-"-
- - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-Y-o-u-T-u-b-e- -/- -J-i-a-n-y-i-n-g- -/- -e-x-t-e-r-n-a-l- -v-i-d-e-o- -l-i-n-k-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - -/->-
-
- - - - - - - - - - -<-l-a-b-e-l- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -i-t-e-m-s---c-e-n-t-e-r- -g-a-p---2-"->-
- - - - - - - - - - - - -<-i-n-p-u-t- -n-a-m-e-=-"-i-s-_-a-c-t-i-v-e-"- -t-y-p-e-=-"-c-h-e-c-k-b-o-x-"- -d-e-f-a-u-l-t-C-h-e-c-k-e-d- -/->-
- - - - - - - - - - - - -<-s-p-a-n->-S-h-o-w- -t-h-i-s- -s-e-s-s-i-o-n-<-/-s-p-a-n->-
- - - - - - - - - - -<-/-l-a-b-e-l->-
-
- - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-i-t- -r-o-u-n-d-e-d---x-l- -b-g---s-l-a-t-e---9-5-0- -p-x---5- -p-y---3- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---w-h-i-t-e- -h-o-v-e-r-:-b-g---s-l-a-t-e---7-0-0-"-
- - - - - - - - - - ->-
- - - - - - - - - - - - -A-d-d- -M-a-j-o-r- -S-e-s-s-i-o-n-
- - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - -<-/-f-o-r-m->-
- - - - - - -<-/-s-e-c-t-i-o-n->-
-
- - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-m-b---1-0- -r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---6- -s-h-a-d-o-w---s-m-"->-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - -E-x-i-s-t-i-n-g- -S-e-s-s-i-o-n-s- -a-n-d- -S-u-b-s-e-s-s-i-o-n-s-
- - - - - - - - -<-/-h-2->-
-
- - - - - - - - -{-s-e-s-s-i-o-n-s-.-l-e-n-g-t-h- -=-=-=- -0- -?- -(-
- - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -t-e-x-t---s-l-a-t-e---6-0-0-"->-N-o- -s-e-s-s-i-o-n-s- -y-e-t-.-<-/-p->-
- - - - - - - - -)- -:- -(-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -s-p-a-c-e---y---6-"->-
- - - - - - - - - - - - -{-s-e-s-s-i-o-n-s-.-m-a-p-(-(-s-e-s-s-i-o-n-)- -=->- -{-
- - - - - - - - - - - - - - -c-o-n-s-t- -w-o-r-k-s-h-o-p- -=- -s-e-s-s-i-o-n-.-w-o-r-k-s-h-o-p-_-i-d-
- - - - - - - - - - - - - - - - -?- -w-o-r-k-s-h-o-p-B-y-I-d-.-g-e-t-(-s-e-s-s-i-o-n-.-w-o-r-k-s-h-o-p-_-i-d-)-
- - - - - - - - - - - - - - - - -:- -n-u-l-l-;-
-
- - - - - - - - - - - - - - -c-o-n-s-t- -c-h-i-l-d-S-u-b-s-e-s-s-i-o-n-s- -=-
- - - - - - - - - - - - - - - - -s-u-b-s-e-s-s-i-o-n-s-B-y-S-e-s-s-i-o-n-I-d-.-g-e-t-(-s-e-s-s-i-o-n-.-i-d-)- -?-?- -[-]-;-
-
- - - - - - - - - - - - - - -r-e-t-u-r-n- -(-
- - - - - - - - - - - - - - - - -<-a-r-t-i-c-l-e-
- - - - - - - - - - - - - - - - - - -k-e-y-=-{-s-e-s-s-i-o-n-.-i-d-}-
- - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---s-l-a-t-e---5-0- -p---5-"-
- - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -f-l-e-x---c-o-l- -j-u-s-t-i-f-y---b-e-t-w-e-e-n- -g-a-p---4- -l-g-:-f-l-e-x---r-o-w- -l-g-:-i-t-e-m-s---s-t-a-r-t-"->-
- - - - - - - - - - - - - - - - - - - - -<-d-i-v->-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---x-s- -f-o-n-t---b-o-l-d- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-2-e-m-]- -t-e-x-t---s-l-a-t-e---4-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -M-a-j-o-r- -S-e-s-s-i-o-n- -路- -O-r-d-e-r- -{-s-e-s-s-i-o-n-.-d-i-s-p-l-a-y-_-o-r-d-e-r- -?-?- -0-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-h-3- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -{-s-e-s-s-i-o-n-.-t-i-t-l-e- -|-|- -"-W-o-r-k-s-h-o-p- -S-e-s-s-i-o-n-"-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-h-3->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -W-o-r-k-s-h-o-p-:- -{-w-o-r-k-s-h-o-p-?-.-t-i-t-l-e- -|-|- -"-U-n-k-n-o-w-n- -w-o-r-k-s-h-o-p-"-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---1- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -D-a-t-e-:- -{-s-e-s-s-i-o-n-.-s-e-s-s-i-o-n-_-d-a-t-e- -|-|- -"---"-}- -路- -T-i-m-e-:-{-"- -"-}-
- - - - - - - - - - - - - - - - - - - - - - - - -{-s-e-s-s-i-o-n-.-s-t-a-r-t-_-t-i-m-e- -|-|- -"---"-}- --- -{-s-e-s-s-i-o-n-.-e-n-d-_-t-i-m-e- -|-|- -"---"-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---1- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -S-t-a-t-u-s-:-{-"- -"-}-
- - - - - - - - - - - - - - - - - - - - - - - - -{-s-e-s-s-i-o-n-.-i-s-_-a-c-t-i-v-e- -=-=-=- -f-a-l-s-e- -?- -"-H-i-d-d-e-n-"- -:- -"-V-i-s-i-b-l-e-"-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - -{-s-e-s-s-i-o-n-.-m-e-d-i-a-_-u-r-l- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---1- -b-r-e-a-k---a-l-l- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - -M-e-d-i-a-:- -{-s-e-s-s-i-o-n-.-m-e-d-i-a-_-u-r-l-}-
- - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
- - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - - - -<-f-o-r-m- -a-c-t-i-o-n-=-{-d-e-l-e-t-e-W-o-r-k-s-h-o-p-S-e-s-s-i-o-n-}->-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t- -t-y-p-e-=-"-h-i-d-d-e-n-"- -n-a-m-e-=-"-i-d-"- -v-a-l-u-e-=-{-s-e-s-s-i-o-n-.-i-d-}- -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---r-e-d---6-0-0- -h-o-v-e-r-:-b-g---r-e-d---5-0-"-
- - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - -D-e-l-e-t-e- -m-a-j-o-r- -s-e-s-s-i-o-n-
- - - - - - - - - - - - - - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - - - - - - - - - - - - - -<-/-f-o-r-m->-
- - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -r-o-u-n-d-e-d---2-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---4-"->-
- - - - - - - - - - - - - - - - - - - - -<-h-4- -c-l-a-s-s-N-a-m-e-=-"-f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -A-d-d- -S-u-b-s-e-s-s-i-o-n-
- - - - - - - - - - - - - - - - - - - - -<-/-h-4->-
-
- - - - - - - - - - - - - - - - - - - - -<-f-o-r-m-
- - - - - - - - - - - - - - - - - - - - - - -a-c-t-i-o-n-=-{-c-r-e-a-t-e-W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-}-
- - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -g-r-i-d- -g-a-p---4-"-
- - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-h-i-d-d-e-n-"-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-s-e-s-s-i-o-n-_-i-d-"-
- - - - - - - - - - - - - - - - - - - - - - - - -v-a-l-u-e-=-{-s-e-s-s-i-o-n-.-i-d-}-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---4- -m-d-:-g-r-i-d---c-o-l-s---2-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-t-i-t-l-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -r-e-q-u-i-r-e-d-
- - - - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-S-u-b-s-e-s-s-i-o-n- -t-i-t-l-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-n-u-m-b-e-r-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -d-e-f-a-u-l-t-V-a-l-u-e-=-{-0-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-D-i-s-p-l-a-y- -o-r-d-e-r-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - - - -/->-
- - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-t-e-x-t-a-r-e-a-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-d-e-s-c-r-i-p-t-i-o-n-"-
- - - - - - - - - - - - - - - - - - - - - - - - -r-o-w-s-=-{-3-}-
- - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-S-u-b-s-e-s-s-i-o-n- -d-e-s-c-r-i-p-t-i-o-n-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-g-r-i-d- -g-a-p---4- -m-d-:-g-r-i-d---c-o-l-s---2-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-s-t-a-r-t-_-t-i-m-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-t-i-m-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-e-n-d-_-t-i-m-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-t-i-m-e-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - - - -/->-
- - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-m-e-e-t-i-n-g-_-u-r-l-"-
- - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-M-e-e-t-i-n-g- -/- -Z-o-o-m- -U-R-L-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-r-e-c-o-r-d-i-n-g-_-u-r-l-"-
- - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-R-e-c-o-r-d-i-n-g- -U-R-L-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-m-a-t-e-r-i-a-l-_-u-r-l-"-
- - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-M-a-t-e-r-i-a-l- -U-R-L-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-S-e-s-s-i-o-n-M-e-d-i-a-U-p-l-o-a-d-e-r- -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-e-x-t-e-r-n-a-l-_-v-i-d-e-o-_-u-r-l-"-
- - - - - - - - - - - - - - - - - - - - - - - - -p-l-a-c-e-h-o-l-d-e-r-=-"-Y-o-u-T-u-b-e- -/- -J-i-a-n-y-i-n-g- -/- -e-x-t-e-r-n-a-l- -v-i-d-e-o- -l-i-n-k-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-u-l-l- -r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -p-x---4- -p-y---3-"-
- - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-l-a-b-e-l- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -i-t-e-m-s---c-e-n-t-e-r- -g-a-p---2-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t- -n-a-m-e-=-"-i-s-_-a-c-t-i-v-e-"- -t-y-p-e-=-"-c-h-e-c-k-b-o-x-"- -d-e-f-a-u-l-t-C-h-e-c-k-e-d- -/->-
- - - - - - - - - - - - - - - - - - - - - - - - -<-s-p-a-n->-S-h-o-w- -t-h-i-s- -s-u-b-s-e-s-s-i-o-n-<-/-s-p-a-n->-
- - - - - - - - - - - - - - - - - - - - - - -<-/-l-a-b-e-l->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-w---f-i-t- -r-o-u-n-d-e-d---x-l- -b-g---s-l-a-t-e---9-5-0- -p-x---5- -p-y---3- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---w-h-i-t-e- -h-o-v-e-r-:-b-g---s-l-a-t-e---7-0-0-"-
- - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - -A-d-d- -S-u-b-s-e-s-s-i-o-n-
- - - - - - - - - - - - - - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - - - - - - - - - - - - - -<-/-f-o-r-m->-
- - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6-"->-
- - - - - - - - - - - - - - - - - - - - -<-h-4- -c-l-a-s-s-N-a-m-e-=-"-f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -S-u-b-s-e-s-s-i-o-n-s-
- - - - - - - - - - - - - - - - - - - - -<-/-h-4->-
-
- - - - - - - - - - - - - - - - - - - - -{-c-h-i-l-d-S-u-b-s-e-s-s-i-o-n-s-.-l-e-n-g-t-h- -=-=-=- -0- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -N-o- -s-u-b-s-e-s-s-i-o-n-s- -y-e-t-.-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - -)- -:- -(-
- - - - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -s-p-a-c-e---y---3-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -{-c-h-i-l-d-S-u-b-s-e-s-s-i-o-n-s-.-m-a-p-(-(-s-u-b-s-e-s-s-i-o-n-)- -=->- -(-
- - - - - - - - - - - - - - - - - - - - - - - - - - -<-d-i-v-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -k-e-y-=-{-s-u-b-s-e-s-s-i-o-n-.-i-d-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---2-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---4-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -f-l-e-x---c-o-l- -j-u-s-t-i-f-y---b-e-t-w-e-e-n- -g-a-p---4- -m-d-:-f-l-e-x---r-o-w- -m-d-:-i-t-e-m-s---s-t-a-r-t-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-d-i-v->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---x-s- -f-o-n-t---b-o-l-d- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-2-e-m-]- -t-e-x-t---s-l-a-t-e---4-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -S-u-b-s-e-s-s-i-o-n- -路- -O-r-d-e-r-{-"- -"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-d-i-s-p-l-a-y-_-o-r-d-e-r- -?-?- -0-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-h-5- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---l-g- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-t-i-t-l-e- -|-|- -"-S-u-b-s-e-s-s-i-o-n-"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-h-5->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -T-i-m-e-:- -{-s-u-b-s-e-s-s-i-o-n-.-s-t-a-r-t-_-t-i-m-e- -|-|- -"---"-}- ---{-"- -"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-e-n-d-_-t-i-m-e- -|-|- -"---"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---1- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -S-t-a-t-u-s-:-{-"- -"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-i-s-_-a-c-t-i-v-e- -=-=-=- -f-a-l-s-e-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -?- -"-H-i-d-d-e-n-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -:- -"-V-i-s-i-b-l-e-"-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-d-e-s-c-r-i-p-t-i-o-n- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -w-h-i-t-e-s-p-a-c-e---p-r-e---w-r-a-p- -t-e-x-t---s-m- -l-e-a-d-i-n-g---6- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-d-e-s-c-r-i-p-t-i-o-n-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -{-s-u-b-s-e-s-s-i-o-n-.-m-e-d-i-a-_-u-r-l- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -b-r-e-a-k---a-l-l- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---5-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -M-e-d-i-a-:- -{-s-u-b-s-e-s-s-i-o-n-.-m-e-d-i-a-_-u-r-l-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -f-l-e-x---w-r-a-p- -g-a-p---2-"->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-L-i-n-k-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -h-r-e-f-=-{-`-/-a-d-m-i-n-/-w-o-r-k-s-h-o-p-s-/-s-u-b-s-e-s-s-i-o-n-s-/-$-{-s-u-b-s-e-s-s-i-o-n-.-i-d-}-/-e-d-i-t-`-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-g---s-l-a-t-e---9-5-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---w-h-i-t-e- -h-o-v-e-r-:-b-g---s-l-a-t-e---7-0-0-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -E-d-i-t- -s-u-b-s-e-s-s-i-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-f-o-r-m- -a-c-t-i-o-n-=-{-d-e-l-e-t-e-W-o-r-k-s-h-o-p-S-u-b-s-e-s-s-i-o-n-}->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-h-i-d-d-e-n-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -n-a-m-e-=-"-i-d-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -v-a-l-u-e-=-{-s-u-b-s-e-s-s-i-o-n-.-i-d-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -/->-
-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---r-e-d---6-0-0- -h-o-v-e-r-:-b-g---r-e-d---5-0-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -D-e-l-e-t-e- -s-u-b-s-e-s-s-i-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-f-o-r-m->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - - - - - - - -)-)-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - - - -)-}-
- - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
- - - - - - - - - - - - - - -)-;-
- - - - - - - - - - - - -}-)-}-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -)-}-
- - - - - - -<-/-s-e-c-t-i-o-n->-
-
- - - - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -p---6- -s-h-a-d-o-w---s-m-"->-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---2-x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - -E-x-i-s-t-i-n-g- -W-o-r-k-s-h-o-p-s-
- - - - - - - - -<-/-h-2->-
-
- - - - - - - - -{-w-o-r-k-s-h-o-p-s-.-l-e-n-g-t-h- -=-=-=- -0- -?- -(-
- - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -t-e-x-t---s-l-a-t-e---6-0-0-"->-N-o- -w-o-r-k-s-h-o-p-s- -y-e-t-.-<-/-p->-
- - - - - - - - -)- -:- -(-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -g-r-i-d- -g-a-p---6- -m-d-:-g-r-i-d---c-o-l-s---2- -l-g-:-g-r-i-d---c-o-l-s---3-"->-
- - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-s-.-m-a-p-(-(-w-o-r-k-s-h-o-p-)- -=->- -{-
- - - - - - - - - - - - - - -c-o-n-s-t- -w-o-r-k-s-h-o-p-S-e-s-s-i-o-n-s- -=-
- - - - - - - - - - - - - - - - -s-e-s-s-i-o-n-s-B-y-W-o-r-k-s-h-o-p-I-d-.-g-e-t-(-w-o-r-k-s-h-o-p-.-i-d-)- -?-?- -[-]-;-
-
- - - - - - - - - - - - - - -r-e-t-u-r-n- -(-
- - - - - - - - - - - - - - - - -<-a-r-t-i-c-l-e-
- - - - - - - - - - - - - - - - - - -k-e-y-=-{-w-o-r-k-s-h-o-p-.-i-d-}-
- - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-o-v-e-r-f-l-o-w---h-i-d-d-e-n- -r-o-u-n-d-e-d---3-x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---2-0-0- -b-g---w-h-i-t-e- -s-h-a-d-o-w---s-m-"-
- - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - -{-g-e-t-W-o-r-k-s-h-o-p-I-m-a-g-e-(-w-o-r-k-s-h-o-p-)- -?- -(-
- - - - - - - - - - - - - - - - - - - - -<-i-m-g-
- - - - - - - - - - - - - - - - - - - - - - -s-r-c-=-{-g-e-t-W-o-r-k-s-h-o-p-I-m-a-g-e-(-w-o-r-k-s-h-o-p-)-}-
- - - - - - - - - - - - - - - - - - - - - - -a-l-t-=-{-w-o-r-k-s-h-o-p-.-t-i-t-l-e- -|-|- -"-W-o-r-k-s-h-o-p-"-}-
- - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-h---4-8- -w---f-u-l-l- -o-b-j-e-c-t---c-o-v-e-r-"-
- - - - - - - - - - - - - - - - - - - - -/->-
- - - - - - - - - - - - - - - - - - -)- -:- -(-
- - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-f-l-e-x- -h---4-8- -i-t-e-m-s---c-e-n-t-e-r- -j-u-s-t-i-f-y---c-e-n-t-e-r- -b-g---s-l-a-t-e---1-0-0- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---5-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -N-o- -i-m-a-g-e-
- - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - -)-}-
-
- - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p---6-"->-
- - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-t-e-x-t---x-s- -f-o-n-t---b-o-l-d- -u-p-p-e-r-c-a-s-e- -t-r-a-c-k-i-n-g---[-0-.-2-e-m-]- -t-e-x-t---s-l-a-t-e---4-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-.-i-s-_-p-u-b-l-i-s-h-e-d- -|-|- -w-o-r-k-s-h-o-p-.-i-s-_-a-c-t-i-v-e-
- - - - - - - - - - - - - - - - - - - - - - - - -?- -"-P-u-b-l-i-s-h-e-d-"-
- - - - - - - - - - - - - - - - - - - - - - - - -:- -"-D-r-a-f-t-"-}-
- - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - -<-h-3- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -t-e-x-t---x-l- -f-o-n-t---b-l-a-c-k- -t-e-x-t---s-l-a-t-e---9-5-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-.-t-i-t-l-e-}-
- - - - - - - - - - - - - - - - - - - - -<-/-h-3->-
-
- - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---2- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -S-l-u-g-:- -{-w-o-r-k-s-h-o-p-.-s-l-u-g- -|-|- -"---"-}-
- - - - - - - - - - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - - - - - - - - - -{-g-e-t-W-o-r-k-s-h-o-p-D-e-s-c-r-i-p-t-i-o-n-(-w-o-r-k-s-h-o-p-)- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -l-i-n-e---c-l-a-m-p---3- -t-e-x-t---s-m- -l-e-a-d-i-n-g---6- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -{-g-e-t-W-o-r-k-s-h-o-p-D-e-s-c-r-i-p-t-i-o-n-(-w-o-r-k-s-h-o-p-)-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---4- -s-p-a-c-e---y---1- -t-e-x-t---s-m- -t-e-x-t---s-l-a-t-e---6-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - -<-p->-S-p-e-a-k-e-r-:- -{-g-e-t-W-o-r-k-s-h-o-p-S-p-e-a-k-e-r-(-w-o-r-k-s-h-o-p-)- -|-|- -"---"-}-<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - -<-p->-D-a-t-e-:- -{-g-e-t-W-o-r-k-s-h-o-p-D-a-t-e-(-w-o-r-k-s-h-o-p-)- -|-|- -"---"-}-<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - -<-p->-F-o-r-m-a-t-:- -{-w-o-r-k-s-h-o-p-.-f-o-r-m-a-t- -|-|- -"---"-}-<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - -<-p->-P-r-i-c-e-:- -{-f-o-r-m-a-t-P-r-i-c-e-(-w-o-r-k-s-h-o-p-)-}-<-/-p->-
- - - - - - - - - - - - - - - - - - - - - - -<-p->-S-e-s-s-i-o-n-s-:- -{-w-o-r-k-s-h-o-p-S-e-s-s-i-o-n-s-.-l-e-n-g-t-h-}-<-/-p->-
- - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - - - - - - - -{-g-e-t-W-o-r-k-s-h-o-p-M-a-t-e-r-i-a-l-(-w-o-r-k-s-h-o-p-)- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-m-t---3- -b-r-e-a-k---a-l-l- -t-e-x-t---x-s- -t-e-x-t---s-l-a-t-e---5-0-0-"->-
- - - - - - - - - - - - - - - - - - - - - - - - -M-a-t-e-r-i-a-l-:- -{-g-e-t-W-o-r-k-s-h-o-p-M-a-t-e-r-i-a-l-(-w-o-r-k-s-h-o-p-)-}-
- - - - - - - - - - - - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-m-t---6- -f-l-e-x- -f-l-e-x---w-r-a-p- -g-a-p---2-"->-
- - - - - - - - - - - - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-.-s-l-u-g- -?- -(-
- - - - - - - - - - - - - - - - - - - - - - - - -<-L-i-n-k-
- - - - - - - - - - - - - - - - - - - - - - - - - - -h-r-e-f-=-{-`-/-w-o-r-k-s-h-o-p-s-/-$-{-w-o-r-k-s-h-o-p-.-s-l-u-g-}-`-}-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---s-l-a-t-e---3-0-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---s-l-a-t-e---7-0-0- -h-o-v-e-r-:-b-g---s-l-a-t-e---5-0-"-
- - - - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - - - -V-i-e-w-
- - - - - - - - - - - - - - - - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - - - - - - - - - - - - - - - -)- -:- -n-u-l-l-}-
-
- - - - - - - - - - - - - - - - - - - - - - -<-L-i-n-k-
- - - - - - - - - - - - - - - - - - - - - - - - -h-r-e-f-=-{-`-/-a-d-m-i-n-/-w-o-r-k-s-h-o-p-s-/-$-{-w-o-r-k-s-h-o-p-.-i-d-}-/-e-d-i-t-`-}-
- - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-g---s-l-a-t-e---9-5-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---w-h-i-t-e- -h-o-v-e-r-:-b-g---s-l-a-t-e---7-0-0-"-
- - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - -E-d-i-t-
- - - - - - - - - - - - - - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - - - - - - - - - - - - - -<-f-o-r-m- -a-c-t-i-o-n-=-{-d-e-l-e-t-e-W-o-r-k-s-h-o-p-}->-
- - - - - - - - - - - - - - - - - - - - - - - - -<-i-n-p-u-t- -t-y-p-e-=-"-h-i-d-d-e-n-"- -n-a-m-e-=-"-i-d-"- -v-a-l-u-e-=-{-w-o-r-k-s-h-o-p-.-i-d-}- -/->-
-
- - - - - - - - - - - - - - - - - - - - - - - - -<-b-u-t-t-o-n-
- - - - - - - - - - - - - - - - - - - - - - - - - - -t-y-p-e-=-"-s-u-b-m-i-t-"-
- - - - - - - - - - - - - - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-r-o-u-n-d-e-d---x-l- -b-o-r-d-e-r- -b-o-r-d-e-r---r-e-d---2-0-0- -p-x---4- -p-y---2- -t-e-x-t---s-m- -f-o-n-t---b-o-l-d- -t-e-x-t---r-e-d---6-0-0- -h-o-v-e-r-:-b-g---r-e-d---5-0-"-
- - - - - - - - - - - - - - - - - - - - - - - - ->-
- - - - - - - - - - - - - - - - - - - - - - - - - - -D-e-l-e-t-e-
- - - - - - - - - - - - - - - - - - - - - - - - -<-/-b-u-t-t-o-n->-
- - - - - - - - - - - - - - - - - - - - - - -<-/-f-o-r-m->-
- - - - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
- - - - - - - - - - - - - - -)-;-
- - - - - - - - - - - - -}-)-}-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -)-}-
- - - - - - -<-/-s-e-c-t-i-o-n->-
- - - - -<-/-m-a-i-n->-
- - -)-;-
-}-