-"-u-s-e- -s-e-r-v-e-r-"-;-
-
-i-m-p-o-r-t- -{- -r-e-v-a-l-i-d-a-t-e-P-a-t-h- -}- -f-r-o-m- -"-n-e-x-t-/-c-a-c-h-e-"-;-
-i-m-p-o-r-t- -{- -r-e-d-i-r-e-c-t- -}- -f-r-o-m- -"-n-e-x-t-/-n-a-v-i-g-a-t-i-o-n-"-;-
-i-m-p-o-r-t- -{- -r-e-q-u-i-r-e-A-d-m-i-n- -}- -f-r-o-m- -"-@-/-l-i-b-/-a-u-t-h-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-s-e-r-v-e-r-"-;-
-
-f-u-n-c-t-i-o-n- -s-l-u-g-i-f-y-(-v-a-l-u-e-:- -s-t-r-i-n-g-)- -{-
- - -r-e-t-u-r-n- -v-a-l-u-e-
- - - - -.-t-o-L-o-w-e-r-C-a-s-e-(-)-
- - - - -.-t-r-i-m-(-)-
- - - - -.-r-e-p-l-a-c-e-(-/-[-^-a---z-0---9-]-+-/-g-,- -"---"-)-
- - - - -.-r-e-p-l-a-c-e-(-/-(-^---|---$-)-+-/-g-,- -"-"-)-;-
-}-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -c-r-e-a-t-e-C-o-u-r-s-e-(-f-o-r-m-D-a-t-a-:- -F-o-r-m-D-a-t-a-)- -{-
- - -c-o-n-s-t- -u-s-e-r- -=- -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -t-i-t-l-e- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-t-i-t-l-e-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -s-l-u-g- -=- -s-l-u-g-i-f-y-(-S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-l-u-g-"-)- -|-|- -t-i-t-l-e-)-)-;-
- - -c-o-n-s-t- -c-a-t-e-g-o-r-y-_-i-d- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-a-t-e-g-o-r-y-_-i-d-"-)- -|-|- -"-"-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n- -=- -S-t-r-i-n-g-(-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-"-)- -?-?- -"-"-
- - -)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -i-n-t-r-o- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-n-t-r-o-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -l-e-v-e-l- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-l-e-v-e-l-"-)- -?-?- -"-B-e-g-i-n-n-e-r-"-)-;-
- - -c-o-n-s-t- -l-a-n-g-u-a-g-e- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-l-a-n-g-u-a-g-e-"-)- -?-?- -"-E-n-g-l-i-s-h-"-)-;-
- - -c-o-n-s-t- -c-o-v-e-r-_-u-r-l- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-o-v-e-r-_-u-r-l-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -p-r-i-c-e-_-c-e-n-t-s- -=- -N-u-m-b-e-r-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-p-r-i-c-e-_-c-e-n-t-s-"-)- -|-|- -0-)-;-
- - -c-o-n-s-t- -c-u-r-r-e-n-c-y- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-u-r-r-e-n-c-y-"-)- -|-|- -"-u-s-d-"-)-.-t-o-L-o-w-e-r-C-a-s-e-(-)-;-
- - -c-o-n-s-t- -s-t-r-i-p-e-_-p-r-i-c-e-_-i-d- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-t-r-i-p-e-_-p-r-i-c-e-_-i-d-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -i-s-_-p-u-b-l-i-s-h-e-d- -=- -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-p-u-b-l-i-s-h-e-d-"-)- -=-=-=- -"-o-n-"-;-
-
- - -c-o-n-s-t- -i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d- -=-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d-"-)- -=-=-=- -"-o-n-"-;-
- - -c-o-n-s-t- -h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r- -=- -N-u-m-b-e-r-(-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r-"-)- -|-|- -0-
- - -)-;-
- - -c-o-n-s-t- -h-o-m-e-_-b-a-d-g-e- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-b-a-d-g-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -"-F-e-a-t-u-r-e-d- -C-o-u-r-s-e-"-;-
- - -c-o-n-s-t- -h-o-m-e-_-c-t-a- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-c-t-a-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -"-V-i-e-w- -C-o-u-r-s-e-"-;-
-
- - -i-f- -(-!-t-i-t-l-e- -|-|- -!-s-l-u-g-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-n-e-w-?-m-e-s-s-a-g-e-=-T-i-t-l-e- -a-n-d- -s-l-u-g- -a-r-e- -r-e-q-u-i-r-e-d-"-)-;-
- - -}-
-
- - -c-o-n-s-t- -{- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-f-r-o-m-(-"-c-o-u-r-s-e-s-"-)-.-i-n-s-e-r-t-(-{-
- - - - -t-i-t-l-e-,-
- - - - -s-l-u-g-,-
- - - - -c-a-t-e-g-o-r-y-_-i-d-,-
- - - - -s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-,-
- - - - -i-n-t-r-o-,-
- - - - -l-e-v-e-l-,-
- - - - -l-a-n-g-u-a-g-e-,-
- - - - -c-o-v-e-r-_-u-r-l-,-
- - - - -p-r-i-c-e-_-c-e-n-t-s-,-
- - - - -c-u-r-r-e-n-c-y-,-
- - - - -s-t-r-i-p-e-_-p-r-i-c-e-_-i-d-,-
- - - - -i-s-_-p-u-b-l-i-s-h-e-d-,-
- - - - -i-n-s-t-r-u-c-t-o-r-_-i-d-:- -u-s-e-r-.-i-d-,-
-
- - - - -i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d-,-
- - - - -h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r-,-
- - - - -h-o-m-e-_-b-a-d-g-e-,-
- - - - -h-o-m-e-_-c-t-a-,-
- - -}-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-
- - - - - - -`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-n-e-w-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-e-r-r-o-r-.-m-e-s-s-a-g-e-)-}-`-
- - - - -)-;-
- - -}-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-c-o-u-r-s-e-s-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-`-/-c-o-u-r-s-e-s-/-$-{-s-l-u-g-}-`-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-
- - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-}-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -u-p-d-a-t-e-C-o-u-r-s-e-(-c-o-u-r-s-e-I-d-:- -s-t-r-i-n-g-,- -f-o-r-m-D-a-t-a-:- -F-o-r-m-D-a-t-a-)- -{-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -t-i-t-l-e- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-t-i-t-l-e-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -s-l-u-g- -=- -s-l-u-g-i-f-y-(-S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-l-u-g-"-)- -|-|- -t-i-t-l-e-)-)-;-
- - -c-o-n-s-t- -c-a-t-e-g-o-r-y-_-i-d- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-a-t-e-g-o-r-y-_-i-d-"-)- -|-|- -"-"-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n- -=- -S-t-r-i-n-g-(-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-"-)- -?-?- -"-"-
- - -)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -i-n-t-r-o- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-n-t-r-o-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -l-e-v-e-l- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-l-e-v-e-l-"-)- -?-?- -"-B-e-g-i-n-n-e-r-"-)-;-
- - -c-o-n-s-t- -l-a-n-g-u-a-g-e- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-l-a-n-g-u-a-g-e-"-)- -?-?- -"-E-n-g-l-i-s-h-"-)-;-
- - -c-o-n-s-t- -c-o-v-e-r-_-u-r-l- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-o-v-e-r-_-u-r-l-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -p-r-i-c-e-_-c-e-n-t-s- -=- -N-u-m-b-e-r-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-p-r-i-c-e-_-c-e-n-t-s-"-)- -|-|- -0-)-;-
- - -c-o-n-s-t- -c-u-r-r-e-n-c-y- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-u-r-r-e-n-c-y-"-)- -|-|- -"-u-s-d-"-)-.-t-o-L-o-w-e-r-C-a-s-e-(-)-;-
- - -c-o-n-s-t- -s-t-r-i-p-e-_-p-r-i-c-e-_-i-d- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-t-r-i-p-e-_-p-r-i-c-e-_-i-d-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -i-s-_-p-u-b-l-i-s-h-e-d- -=- -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-p-u-b-l-i-s-h-e-d-"-)- -=-=-=- -"-o-n-"-;-
-
- - -c-o-n-s-t- -i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d- -=-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d-"-)- -=-=-=- -"-o-n-"-;-
- - -c-o-n-s-t- -h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r- -=- -N-u-m-b-e-r-(-
- - - - -f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r-"-)- -|-|- -0-
- - -)-;-
- - -c-o-n-s-t- -h-o-m-e-_-b-a-d-g-e- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-b-a-d-g-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -"-F-e-a-t-u-r-e-d- -C-o-u-r-s-e-"-;-
- - -c-o-n-s-t- -h-o-m-e-_-c-t-a- -=-
- - - - -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-h-o-m-e-_-c-t-a-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -"-V-i-e-w- -C-o-u-r-s-e-"-;-
-
- - -i-f- -(-!-t-i-t-l-e- -|-|- -!-s-l-u-g-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-
- - - - - - -`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-e-d-i-t-?-m-e-s-s-a-g-e-=-T-i-t-l-e- -a-n-d- -s-l-u-g- -a-r-e- -r-e-q-u-i-r-e-d-`-
- - - - -)-;-
- - -}-
-
- - -c-o-n-s-t- -{- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-c-o-u-r-s-e-s-"-)-
- - - - -.-u-p-d-a-t-e-(-{-
- - - - - - -t-i-t-l-e-,-
- - - - - - -s-l-u-g-,-
- - - - - - -c-a-t-e-g-o-r-y-_-i-d-,-
- - - - - - -s-h-o-r-t-_-d-e-s-c-r-i-p-t-i-o-n-,-
- - - - - - -i-n-t-r-o-,-
- - - - - - -l-e-v-e-l-,-
- - - - - - -l-a-n-g-u-a-g-e-,-
- - - - - - -c-o-v-e-r-_-u-r-l-,-
- - - - - - -p-r-i-c-e-_-c-e-n-t-s-,-
- - - - - - -c-u-r-r-e-n-c-y-,-
- - - - - - -s-t-r-i-p-e-_-p-r-i-c-e-_-i-d-,-
- - - - - - -i-s-_-p-u-b-l-i-s-h-e-d-,-
-
- - - - - - -i-s-_-h-o-m-e-_-h-i-g-h-l-i-g-h-t-e-d-,-
- - - - - - -h-o-m-e-_-h-i-g-h-l-i-g-h-t-_-o-r-d-e-r-,-
- - - - - - -h-o-m-e-_-b-a-d-g-e-,-
- - - - - - -h-o-m-e-_-c-t-a-,-
-
- - - - - - -u-p-d-a-t-e-d-_-a-t-:- -n-e-w- -D-a-t-e-(-)-.-t-o-I-S-O-S-t-r-i-n-g-(-)-,-
- - - - -}-)-
- - - - -.-e-q-(-"-i-d-"-,- -c-o-u-r-s-e-I-d-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-
- - - - - - -`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-e-d-i-t-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-
- - - - - - - - -e-r-r-o-r-.-m-e-s-s-a-g-e-
- - - - - - -)-}-`-
- - - - -)-;-
- - -}-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-c-o-u-r-s-e-s-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-`-/-c-o-u-r-s-e-s-/-$-{-s-l-u-g-}-`-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-
- - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-}-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -c-r-e-a-t-e-L-e-s-s-o-n-(-c-o-u-r-s-e-I-d-:- -s-t-r-i-n-g-,- -f-o-r-m-D-a-t-a-:- -F-o-r-m-D-a-t-a-)- -{-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -t-i-t-l-e- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-t-i-t-l-e-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -c-o-n-t-e-n-t- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-o-n-t-e-n-t-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)-;-
- - -c-o-n-s-t- -v-i-d-e-o-_-u-r-l- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-v-i-d-e-o-_-u-r-l-"-)- -?-?- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-;-
- - -c-o-n-s-t- -p-o-s-i-t-i-o-n- -=- -N-u-m-b-e-r-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-p-o-s-i-t-i-o-n-"-)- -?-?- -1-)-;-
- - -c-o-n-s-t- -i-s-_-p-u-b-l-i-s-h-e-d- -=- -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-p-u-b-l-i-s-h-e-d-"-)- -=-=-=- -"-o-n-"-;-
-
- - -i-f- -(-!-t-i-t-l-e-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-
- - - - - - -`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-l-e-s-s-o-n-s-?-m-e-s-s-a-g-e-=-L-e-s-s-o-n- -t-i-t-l-e- -i-s- -r-e-q-u-i-r-e-d-`-
- - - - -)-;-
- - -}-
-
- - -c-o-n-s-t- -{- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-f-r-o-m-(-"-l-e-s-s-o-n-s-"-)-.-i-n-s-e-r-t-(-{-
- - - - -c-o-u-r-s-e-_-i-d-:- -c-o-u-r-s-e-I-d-,-
- - - - -t-i-t-l-e-,-
- - - - -c-o-n-t-e-n-t-,-
- - - - -v-i-d-e-o-_-u-r-l-,-
- - - - -p-o-s-i-t-i-o-n-,-
- - - - -i-s-_-p-u-b-l-i-s-h-e-d-,-
- - -}-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-
- - - - - - -`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-l-e-s-s-o-n-s-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-
- - - - - - - - -e-r-r-o-r-.-m-e-s-s-a-g-e-
- - - - - - -)-}-`-
- - - - -)-;-
- - -}-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-c-o-u-r-s-e-s-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-l-e-s-s-o-n-s-`-)-;-
-
- - -r-e-d-i-r-e-c-t-(-`-/-a-d-m-i-n-/-c-o-u-r-s-e-s-/-$-{-c-o-u-r-s-e-I-d-}-/-l-e-s-s-o-n-s-`-)-;-
-}-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -d-e-l-e-t-e-C-o-u-r-s-e-(-c-o-u-r-s-e-I-d-:- -s-t-r-i-n-g-)- -{-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-f-r-o-m-(-"-c-o-u-r-s-e-s-"-)-.-d-e-l-e-t-e-(-)-.-e-q-(-"-i-d-"-,- -c-o-u-r-s-e-I-d-)-;-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-c-o-u-r-s-e-s-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-
- - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-c-o-u-r-s-e-s-"-)-;-
-}-