-i-m-p-o-r-t- -L-i-n-k- -f-r-o-m- -"-n-e-x-t-/-l-i-n-k-"-;--
-i-m-p-o-r-t- -t-y-p-e- -R-e-a-c-t- -f-r-o-m- -"-r-e-a-c-t-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-s-e-r-v-e-r-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-a-d-m-i-n-"-;-
-i-m-p-o-r-t- -{- -g-e-t-H-o-m-e-p-a-g-e-C-o-n-t-e-n-t-S-l-o-t-s- -}- -f-r-o-m- -"-@-/-l-i-b-/-h-o-m-e-p-a-g-e---c-o-n-t-e-n-t-"-;-
-
-i-m-p-o-r-t- -H-o-m-e-C-o-n-t-r-o-l-P-a-n-e-l-B-u-t-t-o-n- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-H-o-m-e-C-o-n-t-r-o-l-P-a-n-e-l-B-u-t-t-o-n-"-;-
-i-m-p-o-r-t- -D-y-n-a-m-i-c-H-o-m-e-S-h-o-w-c-a-s-e- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-D-y-n-a-m-i-c-H-o-m-e-S-h-o-w-c-a-s-e-"-;-
-i-m-p-o-r-t- -H-o-m-e-H-i-g-h-l-i-g-h-t-e-d-C-o-u-r-s-e-s- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-H-o-m-e-H-i-g-h-l-i-g-h-t-e-d-C-o-u-r-s-e-s-"-;-
-i-m-p-o-r-t- -H-o-m-e-M-e-d-i-a-S-h-o-w-c-a-s-e- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-H-o-m-e-M-e-d-i-a-S-h-o-w-c-a-s-e-"-;-
-i-m-p-o-r-t- -L-a-t-e-s-t-W-o-r-k-s-h-o-p-V-i-d-e-o-s- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-L-a-t-e-s-t-W-o-r-k-s-h-o-p-V-i-d-e-o-s-"-;-
-i-m-p-o-r-t- -N-l-p-A-t-t-r-a-c-t-i-o-n-S-e-c-t-i-o-n- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-N-l-p-A-t-t-r-a-c-t-i-o-n-S-e-c-t-i-o-n-"-;-
-i-m-p-o-r-t- -M-o-u-C-o-l-l-a-b-o-r-a-t-i-o-n-S-e-c-t-i-o-n- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-M-o-u-C-o-l-l-a-b-o-r-a-t-i-o-n-S-e-c-t-i-o-n-"-;-
-i-m-p-o-r-t- -D-y-n-a-m-i-c-P-o-s-t-e-r-S-l-i-d-e-r- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-D-y-n-a-m-i-c-P-o-s-t-e-r-S-l-i-d-e-r-"-;--
-i-m-p-o-r-t- -L-a-t-e-s-t-E-v-e-n-t-s-H-o-m-e-S-e-c-t-i-o-n- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-L-a-t-e-s-t-E-v-e-n-t-s-H-o-m-e-S-e-c-t-i-o-n-"-;--
-i-m-p-o-r-t- -P-r-e-v-i-o-u-s-C-a-s-e-s-S-h-o-w-c-a-s-e- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-P-r-e-v-i-o-u-s-C-a-s-e-s-S-h-o-w-c-a-s-e-"-;--
-i-m-p-o-r-t- -P-a-p-e-r-T-y-p-e-w-r-i-t-e-r-L-i-n-e- -f-r-o-m- -"-@-/-c-o-m-p-o-n-e-n-t-s-/-P-a-p-e-r-T-y-p-e-w-r-i-t-e-r-L-i-n-e-"-;-
-
-t-y-p-e- -S-t-a-t-C-a-r-d- -=- -{-
- - -l-a-b-e-l-:- -s-t-r-i-n-g-;-
- - -v-a-l-u-e-:- -n-u-m-b-e-r-;-
- - -h-r-e-f-:- -s-t-r-i-n-g-;-
-}-;-
-
-t-y-p-e- -S-l-o-t- -=- -{-
- - -k-e-y-:- -s-t-r-i-n-g-;-
- - -l-a-b-e-l-:- -s-t-r-i-n-g-;-
- - -t-i-t-l-e-:- -s-t-r-i-n-g-;-
- - -b-o-d-y-:- -s-t-r-i-n-g-;-
- - -h-r-e-f-:- -s-t-r-i-n-g-;-
- - -i-s-_-a-c-t-i-v-e-:- -b-o-o-l-e-a-n-;-
- - -s-o-r-t-_-o-r-d-e-r-:- -n-u-m-b-e-r-;-
-}-;-
-
-c-o-n-s-t- -i-n-t-r-o-C-a-r-d-s- -=- -[-
- - -{-
- - - - -b-a-d-g-e-:- -"-L-D-"-,-
- - - - -t-i-t-l-e-:- -"-L-a-n-g-u-a-g-e- -d-a-t-a-"-,-
- - - - -b-o-d-y-:- -"-C-o-r-p-u-s- -c-o-n-s-t-r-u-c-t-i-o-n- -a-n-d- -a-n-n-o-t-a-t-i-o-n- -p-i-p-e-l-i-n-e-s- -w-i-t-h- -t-h-e- -c-a-r-e- -o-f- -a- -c-r-i-t-i-c-a-l- -e-d-i-t-i-o-n-.-"-,-
- - - - -c-o-l-o-r-:- -"-p-e-r-i-"-,-
- - -}-,-
- - -{-
- - - - -b-a-d-g-e-:- -"-M-T-"-,-
- - - - -t-i-t-l-e-:- -"-T-r-a-n-s-l-a-t-i-o-n- -t-e-c-h-"-,-
- - - - -b-o-d-y-:- -"-M-T- -e-v-a-l-u-a-t-i-o-n- -a-n-d- -t-e-r-m-i-n-o-l-o-g-y- -s-y-s-t-e-m-s- -w-i-t-h- -h-u-m-a-n-s- -f-i-r-m-l-y- -i-n- -t-h-e- -l-o-o-p-.-"-,-
- - - - -c-o-l-o-r-:- -"-b-u-t-t-e-r-"-,-
- - -}-,-
- - -{-
- - - - -b-a-d-g-e-:- -"-A-I-"-,-
- - - - -t-i-t-l-e-:- -"-E-d-u-c-a-t-i-o-n-"-,-
- - - - -b-o-d-y-:- -"-C-o-u-r-s-e-s- -t-h-a-t- -t-a-k-e- -h-u-m-a-n-i-s-t-s- -f-r-o-m- -s-p-r-e-a-d-s-h-e-e-t-s- -t-o- -w-o-r-k-i-n-g- -N-L-P- -p-i-p-e-l-i-n-e-s-.-"-,-
- - - - -c-o-l-o-r-:- -"-c-o-r-a-l-"-,-
- - -}-,-
-]-;-
-
-f-u-n-c-t-i-o-n- -g-e-t-S-l-o-t-(-s-l-o-t-s-:- -R-e-c-o-r-d-<-s-t-r-i-n-g-,- -S-l-o-t->-,- -k-e-y-:- -s-t-r-i-n-g-)- -{-
- - -r-e-t-u-r-n- -s-l-o-t-s-[-k-e-y-]-;-
-}-
-
-f-u-n-c-t-i-o-n- -F-l-o-a-t-i-n-g-L-e-t-t-e-r-s-(-)- -{-
- - -c-o-n-s-t- -l-e-t-t-e-r-s- -=- -[-"-l-"-,- -"-a-"-,- -"-n-"-,- -"-g-"-,- -"-u-"-,- -"-a-"-,- -"-g-"-,- -"-e-"-,- -"-d-"-,- -"-a-"-,- -"-t-"-,- -"-a-"-]-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---l-e-t-t-e-r-s-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - -{-l-e-t-t-e-r-s-.-m-a-p-(-(-l-e-t-t-e-r-,- -i-n-d-e-x-)- -=->- -(-
- - - - - - - - -<-s-p-a-n- -k-e-y-=-{-`-$-{-l-e-t-t-e-r-}---$-{-i-n-d-e-x-}-`-}->-{-l-e-t-t-e-r-}-<-/-s-p-a-n->-
- - - - - - -)-)-}-
- - - - -<-/-d-i-v->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -H-e-r-o-S-e-c-t-i-o-n-(-{-
- - -s-l-o-t-s-,-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-,-
-}-:- -{-
- - -s-l-o-t-s-:- -R-e-c-o-r-d-<-s-t-r-i-n-g-,- -S-l-o-t->-;-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-:- -b-o-o-l-e-a-n-;-
-}-)- -{-
- - -c-o-n-s-t- -t-i-t-l-e- -=- -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-t-i-t-l-e-"-)-;-
- - -c-o-n-s-t- -s-u-b-t-i-t-l-e- -=- -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-s-u-b-t-i-t-l-e-"-)-;-
- - -c-o-n-s-t- -t-y-p-i-n-g-M-e-s-s-a-g-e-s- -=- -[-
- - - - -s-u-b-t-i-t-l-e-?-.-t-i-t-l-e-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-t-y-p-i-n-g-_-0-1-"-)-?-.-t-i-t-l-e-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-t-y-p-i-n-g-_-0-2-"-)-?-.-t-i-t-l-e-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-t-y-p-i-n-g-_-0-3-"-)-?-.-t-i-t-l-e-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-t-y-p-i-n-g-_-0-4-"-)-?-.-t-i-t-l-e-,-
- - -]-.-f-i-l-t-e-r-(-B-o-o-l-e-a-n-)- -a-s- -s-t-r-i-n-g-[-]-;-
- - -c-o-n-s-t- -p-r-i-m-a-r-y- -=- -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-p-r-i-m-a-r-y-_-b-u-t-t-o-n-"-)-;-
- - -c-o-n-s-t- -s-e-c-o-n-d-a-r-y- -=- -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-h-e-r-o-_-s-e-c-o-n-d-a-r-y-_-b-u-t-t-o-n-"-)-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---e-l-l-i-p-s-u-s---h-e-r-o-"->-
- - - - - - -<-F-l-o-a-t-i-n-g-L-e-t-t-e-r-s- -/->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---p-l-a-n-e---d-o-o-d-l-e-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -1-8-0- -1-5-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-2- -8-2- -L-1-6-0- -1-8- -L-9-0- -1-3-2- -L-7-2- -9-2- -L-1-2- -8-2- -Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-7-2- -9-2- -L-1-6-0- -1-8-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---p-u-r-p-l-e---c-u-r-s-o-r-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -8-0- -9-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-2- -8- -L-6-8- -4-8- -L-4-3- -5-4- -L-3-4- -8-2- -Z-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---c-e-n-t-e-r-"->-
- - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-"- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---l-o-g-o- -p-a-p-e-r---r-e-v-"- -a-r-i-a---l-a-b-e-l-=-"-L-e-x-D-a-t-a- -h-o-m-e-"->-
- - - - - - - - - - -<-s-p-a-n->-L-e-x-D-a-t-a-<-/-s-p-a-n->-
- - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - -<-h-1- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-{-t-i-t-l-e-?-.-t-i-t-l-e- -|-|- -"-W-r-i-t-e- -l-i-k-e- -a- -h-u-m-a-n-.-"-}-<-/-h-1->-
-
- - - - - - - - -<-P-a-p-e-r-T-y-p-e-w-r-i-t-e-r-L-i-n-e- -m-e-s-s-a-g-e-s-=-{-t-y-p-i-n-g-M-e-s-s-a-g-e-s-}- -/->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---a-c-t-i-o-n-s- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---b-t-n-"- -h-r-e-f-=-"-/-s-i-g-n-u-p-"->-
- - - - - - - - - - - - -R-e-g-i-s-t-e-r-
- - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---b-t-n- -p-a-p-e-r---h-e-r-o---b-t-n---g-h-o-s-t-"- -h-r-e-f-=-"-/-l-o-g-i-n-"->-
- - - - - - - - - - - - -L-o-g- -i-n-
- - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-e-r-o---b-t-n- -p-a-p-e-r---h-e-r-o---b-t-n---o-u-t-l-i-n-e-"- -h-r-e-f-=-"-/-c-o-u-r-s-e-s-"->-
- - - - - - - - - - - - -B-r-o-w-s-e- -c-o-u-r-s-e-s-
- - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e- -?- -(-
- - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-a-d-m-i-n-/-h-o-m-e-p-a-g-e---c-o-n-t-e-n-t-"- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---e-d-i-t---h-o-m-e-p-a-g-e-"->-
- - - - - - - - - - - - -E-d-i-t- -h-o-m-e-p-a-g-e- -c-o-n-t-e-n-t-
- - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - -)- -:- -n-u-l-l-}-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -S-t-r-i-p-S-e-c-t-i-o-n-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-t-r-i-p-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-t-r-i-p---t-r-a-c-k-"->-
- - - - - - - - -<-s-p-a-n->-
- - - - - - - - - - -*- -m-a-d-e- -f-o-r- -l-a-n-g-u-a-g-e- -p-e-o-p-l-e- -*- -c-o-r-p-o-r-a- -w-i-t-h- -c-h-a-r-a-c-t-e-r- -*- -h-u-m-a-n---a-n-n-o-t-a-t-e-d-
- - - - - - - - - - -w-o-r-k- -*- -b-u-i-l-t- -b-y- -h-u-m-a-n-i-s-t-s- -*- -h-o-n-e-s-t- -b-e-n-c-h-m-a-r-k-s- -*-
- - - - - - - - -<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-
- - - - - - - - - - -*- -m-a-d-e- -f-o-r- -l-a-n-g-u-a-g-e- -p-e-o-p-l-e- -*- -c-o-r-p-o-r-a- -w-i-t-h- -c-h-a-r-a-c-t-e-r- -*- -h-u-m-a-n---a-n-n-o-t-a-t-e-d-
- - - - - - - - - - -w-o-r-k- -*- -b-u-i-l-t- -b-y- -h-u-m-a-n-i-s-t-s- -*- -h-o-n-e-s-t- -b-e-n-c-h-m-a-r-k-s- -*-
- - - - - - - - -<-/-s-p-a-n->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-d-i-v->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -S-e-c-t-i-o-n-H-e-a-d-(-{- -k-i-c-k-e-r-,- -t-i-t-l-e- -}-:- -{- -k-i-c-k-e-r-:- -s-t-r-i-n-g-;- -t-i-t-l-e-:- -s-t-r-i-n-g- -}-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-e-c-t-i-o-n---h-e-a-d-"->-
- - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---k-i-c-k-e-r- -p-a-p-e-r---r-e-v-"->-{-k-i-c-k-e-r-}-<-/-s-p-a-n->-
- - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-{-t-i-t-l-e-}-<-/-h-2->-
- - - - -<-/-d-i-v->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -I-n-t-r-o-S-e-c-t-i-o-n-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-l-o-c-k- -p-a-p-e-r---p-a-g-e- -p-a-p-e-r---c-e-n-t-e-r-"- -i-d-=-"-i-n-t-r-o-d-u-c-t-i-o-n-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-S-e-c-t-i-o-n-H-e-a-d-
- - - - - - - - - - -k-i-c-k-e-r-=-"-M-a-d-e- -f-o-r- -l-a-n-g-u-a-g-e- -p-e-o-p-l-e-"-
- - - - - - - - - - -t-i-t-l-e-=-"-T-o-o-l-s- -f-o-r- -c-o-r-p-o-r-a-,- -l-a-n-g-u-a-g-e- -d-a-t-a-,- -a-n-d- -h-u-m-a-n---c-e-n-t-e-r-e-d- -A-I-.-"-
- - - - - - - - -/->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-t-i-c-k-e-r-s-"->-
- - - - - - - - - - -{-i-n-t-r-o-C-a-r-d-s-.-m-a-p-(-(-c-a-r-d-,- -i-n-d-e-x-)- -=->- -(-
- - - - - - - - - - - - -<-a-r-t-i-c-l-e-
- - - - - - - - - - - - - - -k-e-y-=-{-c-a-r-d-.-t-i-t-l-e-}-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-t-i-c-k-e-r- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"-
- - - - - - - - - - - - ->-
- - - - - - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-{-`-p-a-p-e-r---e-m-o-j-i---b-a-d-g-e- -p-a-p-e-r---b-a-d-g-e---$-{-c-a-r-d-.-c-o-l-o-r-}-`-}->-
- - - - - - - - - - - - - - - - -{-c-a-r-d-.-b-a-d-g-e-}-
- - - - - - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - - - - - -<-h-3->-{-c-a-r-d-.-t-i-t-l-e-}-<-/-h-3->-
- - - - - - - - - - - - - - -<-p->-{-c-a-r-d-.-b-o-d-y-}-<-/-p->-
- - - - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
- - - - - - - - - - -)-)-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -D-a-s-h-b-o-a-r-d-S-e-c-t-i-o-n-(-)- -{--
- - -r-e-t-u-r-n- -n-u-l-l-;--
-}-
-
-f-u-n-c-t-i-o-n- -P-a-p-e-r-P-a-n-e-l-(-{-
- - -k-i-c-k-e-r-,-
- - -t-i-t-l-e-,-
- - -c-h-i-l-d-r-e-n-,-
- - -i-d-,-
-}-:- -{-
- - -k-i-c-k-e-r-:- -s-t-r-i-n-g-;-
- - -t-i-t-l-e-:- -s-t-r-i-n-g-;-
- - -c-h-i-l-d-r-e-n-:- -R-e-a-c-t-.-R-e-a-c-t-N-o-d-e-;-
- - -i-d-?-:- -s-t-r-i-n-g-;-
-}-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-l-o-c-k- -p-a-p-e-r---p-a-g-e-"- -i-d-=-{-i-d-}->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-S-e-c-t-i-o-n-H-e-a-d- -k-i-c-k-e-r-=-{-k-i-c-k-e-r-}- -t-i-t-l-e-=-{-t-i-t-l-e-}- -/->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---d-y-n-a-m-i-c---p-a-n-e-l- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-{-c-h-i-l-d-r-e-n-}-<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -V-i-d-e-o-S-e-c-t-i-o-n-(-{-
- - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-,-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-,-
- - -s-l-o-t-s-,-
-}-:- -{-
- - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-:- -a-n-y-[-]-;-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-:- -b-o-o-l-e-a-n-;-
- - -s-l-o-t-s-:- -R-e-c-o-r-d-<-s-t-r-i-n-g-,- -S-l-o-t->-;-
-}-)- -{-
- - -c-o-n-s-t- -v-i-d-e-o-S-l-o-t-s- -=- -[-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-v-i-d-e-o-_-s-l-o-t-_-0-1-"-)-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-v-i-d-e-o-_-s-l-o-t-_-0-2-"-)-,-
- - -]-.-f-i-l-t-e-r-(-B-o-o-l-e-a-n-)-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-l-o-c-k- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-v-i-d-e-o-s-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-S-e-c-t-i-o-n-H-e-a-d- -k-i-c-k-e-r-=-"-V-i-d-e-o-s-"- -t-i-t-l-e-=-"-V-i-d-e-o-s-,- -p-r-e-v-i-e-w-s-,- -a-n-d- -m-e-d-i-a- -h-i-g-h-l-i-g-h-t-s-.-"- -/->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---d-y-n-a-m-i-c---p-a-n-e-l- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - -<-H-o-m-e-M-e-d-i-a-S-h-o-w-c-a-s-e-
- - - - - - - - - - - - -v-i-d-e-o-s-=-{-h-o-m-e-p-a-g-e-V-i-d-e-o-s-}-
- - - - - - - - - - - - -c-a-n-M-a-n-a-g-e-=-{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-}-
- - - - - - - - - - -/->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---d-y-n-a-m-i-c---p-a-n-e-l- -p-a-p-e-r---d-y-n-a-m-i-c---p-a-n-e-l---g-a-p- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - -<-L-a-t-e-s-t-W-o-r-k-s-h-o-p-V-i-d-e-o-s- -/->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-l-o-t---g-r-i-d-"->-
- - - - - - - - - - -{-v-i-d-e-o-S-l-o-t-s-.-m-a-p-(-(-s-l-o-t-)- -=->- -(-
- - - - - - - - - - - - -<-L-i-n-k-
- - - - - - - - - - - - - - -k-e-y-=-{-s-l-o-t-.-k-e-y-}-
- - - - - - - - - - - - - - -h-r-e-f-=-{-s-l-o-t-.-h-r-e-f- -|-|- -"-/-m-a-n-a-g-e-r-/-h-o-m-e-p-a-g-e---v-i-d-e-o-s-"-}-
- - - - - - - - - - - - - - -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-l-o-t---c-a-r-d- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"-
- - - - - - - - - - - - ->-
- - - - - - - - - - - - - - -<-s-p-a-n->-{-s-l-o-t-.-l-a-b-e-l-}-<-/-s-p-a-n->-
- - - - - - - - - - - - - - -<-h-3->-{-s-l-o-t-.-t-i-t-l-e-}-<-/-h-3->-
- - - - - - - - - - - - - - -<-p->-{-s-l-o-t-.-b-o-d-y-}-<-/-p->-
- - - - - - - - - - - - - - -<-b->-M-a-n-a-g-e- -v-i-d-e-o-s- ---&-g-t-;-<-/-b->-
- - - - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - - - -)-)-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -M-e-s-s-a-g-e-S-e-c-t-i-o-n-(-{- -s-l-o-t-s- -}-:- -{- -s-l-o-t-s-:- -R-e-c-o-r-d-<-s-t-r-i-n-g-,- -S-l-o-t->- -}-)- -{-
- - -c-o-n-s-t- -m-e-s-s-a-g-e-S-l-o-t-s- -=- -[-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-m-e-s-s-a-g-e-_-s-l-o-t-_-0-1-"-)-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-m-e-s-s-a-g-e-_-s-l-o-t-_-0-2-"-)-,-
- - - - -g-e-t-S-l-o-t-(-s-l-o-t-s-,- -"-m-e-s-s-a-g-e-_-s-l-o-t-_-0-3-"-)-,-
- - -]-.-f-i-l-t-e-r-(-B-o-o-l-e-a-n-)-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-l-o-c-k- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-m-e-s-s-a-g-e-s-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-S-e-c-t-i-o-n-H-e-a-d- -k-i-c-k-e-r-=-"-M-e-s-s-a-g-e-s-"- -t-i-t-l-e-=-"-M-e-s-s-a-g-e-s-,- -a-n-n-o-u-n-c-e-m-e-n-t-s-,- -a-n-d- -u-p-d-a-t-e-s-.-"- -/->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-l-o-t---g-r-i-d-"->-
- - - - - - - - - - -{-m-e-s-s-a-g-e-S-l-o-t-s-.-m-a-p-(-(-s-l-o-t-)- -=->- -(-
- - - - - - - - - - - - -<-a-r-t-i-c-l-e- -k-e-y-=-{-s-l-o-t-.-k-e-y-}- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---s-l-o-t---c-a-r-d- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - - - - - -<-s-p-a-n->-{-s-l-o-t-.-l-a-b-e-l-}-<-/-s-p-a-n->-
- - - - - - - - - - - - - - -<-h-3->-{-s-l-o-t-.-t-i-t-l-e-}-<-/-h-3->-
- - - - - - - - - - - - - - -<-p->-{-s-l-o-t-.-b-o-d-y-}-<-/-p->-
- - - - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
- - - - - - - - - - -)-)-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -S-t-a-n-c-e-B-a-n-d-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-a-n-d- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-s-t-a-n-c-e-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---k-i-c-k-e-r- -p-a-p-e-r---r-e-v-"->-A- -p-r-i-n-c-i-p-l-e-d- -a-l-t-e-r-n-a-t-i-v-e-<-/-s-p-a-n->-
-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-B-y- -h-u-m-a-n-i-s-t-s-,- -f-o-r- -h-u-m-a-n-i-s-t-s-.-<-/-h-2->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-a-d-g-e-s-"->-
- - - - - - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-a-d-g-e- -p-a-p-e-r---r-e-v-"->-Y-o-u-r- -d-a-t-a- -i-s- -y-o-u-r-s-.-<-/-s-p-a-n->-
- - - - - - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-a-d-g-e- -p-a-p-e-r---b-a-d-g-e---b-u-t-t-e-r- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - - - -H-u-m-a-n---a-n-n-o-t-a-t-e-d- -w-o-r-k-.-
- - - - - - - - - - -<-/-s-p-a-n->-
- - - - - - - - - - -<-s-p-a-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-a-d-g-e- -p-a-p-e-r---b-a-d-g-e---c-o-r-a-l- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - - - -H-o-n-e-s-t- -b-e-n-c-h-m-a-r-k-s-.-
- - - - - - - - - - -<-/-s-p-a-n->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-
-f-u-n-c-t-i-o-n- -L-e-x-D-a-t-a-D-a-r-k-S-t-o-r-y-S-e-c-t-i-o-n-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---d-a-r-k---s-t-o-r-y- -p-a-p-e-r---p-a-g-e-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---d-a-r-k---d-o-o-d-l-e- -l-e-x---d-a-r-k---d-o-o-d-l-e---l-e-f-t-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -2-2-0- -1-7-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-3-5- -1-1-6-h-9-2-M-5-2- -9-4-h-7-8-M-6-7- -7-3-h-5-6-M-5-2- -4-5-h-7-8-l-1-8- -4-9---1-8- -4-9-H-5-2-L-3-4- -9-4-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-4-2- -9-4-h-4-5-M-1-5-8- -7-7-l-2-8- -1-7---2-8- -1-7-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---d-a-r-k---d-o-o-d-l-e- -l-e-x---d-a-r-k---d-o-o-d-l-e---r-i-g-h-t-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -2-2-0- -1-8-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-1-2- -1-4-2-V-4-5-M-1-1-2- -4-5-l-4-5- -2-8-M-1-1-2- -4-5- -6-6- -7-6-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-7-6- -8-9-c---2-1---1-8---4-7- -1-1---2-0- -3-4- -8- -7- -2-0- -1-3- -2-0- -1-3-s-1-5---1-0- -2-2---2-1-c-8---1-3---7---2-5---2-2---2-6-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-4-1- -8-9-c-2-1---1-8- -4-7- -1-1- -2-0- -3-4---8- -7---2-0- -1-3---2-0- -1-3-s---1-5---1-0---2-2---2-1-c---8---1-3- -7---2-5- -2-2---2-6-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-7-5- -1-5-4-h-7-5-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p- -l-e-x---d-a-r-k---s-t-o-r-y---i-n-n-e-r-"->-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -O-n-e- -p-l-a-c-e- -f-o-r- -c-o-r-p-o-r-a-,- -a-n-n-o-t-a-t-i-o-n-,- -a-n-d- -A-I- -w-o-r-k-f-l-o-w-s-.-
- - - - - - - - -<-/-h-2->-
-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -L-e-x-D-a-t-a- -b-r-i-n-g-s- -c-o-u-r-s-e-s-,- -r-e-s-e-a-r-c-h- -t-o-o-l-s-,- -N-L-P- -w-o-r-k-f-l-o-w-s-,- -t-r-a-n-s-l-a-t-i-o-n-
- - - - - - - - - - -t-e-c-h-n-o-l-o-g-y-,- -a-n-d- -h-u-m-a-n---c-e-n-t-e-r-e-d- -A-I- -t-r-a-i-n-i-n-g- -i-n-t-o- -o-n-e- -l-a-n-g-u-a-g-e---d-a-t-a-
- - - - - - - - - - -s-t-u-d-i-o-.-
- - - - - - - - -<-/-p->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -L-e-x-D-a-t-a-M-a-n-i-f-e-s-t-o-S-e-c-t-i-o-n-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-n-i-f-e-s-t-o- -p-a-p-e-r---p-a-g-e-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -P-l-e-n-t-y- -o-f- -A-I- -t-o-o-l-s- -a-r-e- -m-a-d-e- -f-o-r- -g-e-n-e-r-i-c- -p-r-o-m-p-t-s-,- -d-a-s-h-b-o-a-r-d-s-,- -a-n-d-
- - - - - - - - - - -a-u-t-o-m-a-t-i-o-n-.- -<-e-m->-T-h-a-t- -i-s- -n-o-t- -u-s-.-<-/-e-m->-
- - - - - - - - -<-/-p->-
-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -L-e-x-D-a-t-a- -i-s- -h-e-r-e- -t-o- -h-e-l-p- -l-a-n-g-u-a-g-e- -r-e-s-e-a-r-c-h-e-r-s- -b-u-i-l-d- -c-o-r-p-o-r-a-,- -e-v-a-l-u-a-t-e-
- - - - - - - - - - -t-r-a-n-s-l-a-t-i-o-n-,- -t-e-a-c-h- -w-i-t-h- -e-v-i-d-e-n-c-e-,- -a-n-d- -u-s-e- -A-I- -w-i-t-h- -h-u-m-a-n- -j-u-d-g-m-e-n-t-
- - - - - - - - - - -<-s-p-a-n->- -i-n- -a-l-l- -i-t-s- -f-o-r-m-s-.-<-/-s-p-a-n->-
- - - - - - - - -<-/-p->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-n-i-f-e-s-t-o---d-o-o-d-l-e-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -3-2-0- -2-2-0-"->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-6-5- -1-6-6-c-3-8---4-4- -8-9---6-3- -1-5-2---5-6-"- -/->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-2-0-5- -8-7-l-3-2- -2-3---3-6- -1-1-"- -/->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-5-5- -1-7-6-h-8-3-M-7-4- -1-5-6-h-6-0-M-9-4- -1-3-6-h-3-8-"- -/->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-2-0-5- -1-5-1-c-2-6---3-2- -5-4---3-5- -8-0---8-"- -/->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-2-3-9- -1-1-1-l-2-0- -1-7- -2-2---3-3-"- -/->-
- - - - - - - - - - - - -<-p-a-t-h- -d-=-"-M-3-7- -6-6-l-1-1- -1-1-M-4-8- -6-6- -3-7- -7-7-M-2-8-3- -5-5-l-1-1- -1-1-M-2-9-4- -5-5-l---1-1- -1-1-"- -/->-
- - - - - - - - - - -<-/-s-v-g->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -L-e-x-D-a-t-a-R-e-s-e-a-r-c-h-T-o-o-l-s-S-e-c-t-i-o-n-(-)- -{-
- - -c-o-n-s-t- -c-a-r-d-s- -=- -[-
- - - - -{-
- - - - - - -t-i-t-l-e-:- -"-C-o-r-p-u-s- -d-e-s-i-g-n-"-,-
- - - - - - -b-o-d-y-:- -"-C-o-l-l-e-c-t-,- -c-l-e-a-n-,- -s-e-g-m-e-n-t-,- -d-o-c-u-m-e-n-t-,- -a-n-d- -p-r-e-p-a-r-e- -m-u-l-t-i-l-i-n-g-u-a-l- -t-e-x-t- -d-a-t-a- -f-o-r- -r-e-s-e-a-r-c-h-.-"-,-
- - - - -}-,-
- - - - -{-
- - - - - - -t-i-t-l-e-:- -"-N-L-P- -w-o-r-k-f-l-o-w-s-"-,-
- - - - - - -b-o-d-y-:- -"-M-o-v-e- -f-r-o-m- -r-a-w- -t-e-x-t- -t-o- -t-o-k-e-n-i-z-a-t-i-o-n-,- -a-n-n-o-t-a-t-i-o-n-,- -e-m-b-e-d-d-i-n-g-s-,- -t-o-p-i-c- -m-o-d-e-l-s-,- -a-n-d- -e-v-a-l-u-a-t-i-o-n-.-"-,-
- - - - -}-,-
- - - - -{-
- - - - - - -t-i-t-l-e-:- -"-T-r-a-n-s-l-a-t-i-o-n- -t-e-c-h-n-o-l-o-g-y-"-,-
- - - - - - -b-o-d-y-:- -"-S-t-u-d-y- -m-a-c-h-i-n-e- -t-r-a-n-s-l-a-t-i-o-n-,- -t-e-r-m-i-n-o-l-o-g-y-,- -q-u-a-l-i-t-y- -e-s-t-i-m-a-t-i-o-n-,- -a-n-d- -h-u-m-a-n---A-I- -r-e-v-i-s-i-o-n-.-"-,-
- - - - -}-,-
- - -]-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---s-e-c-t-i-o-n- -p-a-p-e-r---p-a-g-e-"- -d-a-t-a---p-a-p-e-r---c-o-v-e-r->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---v-i-s-u-a-l-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---s-c-r-e-e-n-"->-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---s-i-d-e-b-a-r-"->-
- - - - - - - - - - - - -<-s-p-a-n->-M-y- -w-o-r-k-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-S-h-a-r-e-d-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-S-e-t-t-i-n-g-s-<-/-s-p-a-n->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---g-r-i-d-"->-
- - - - - - - - - - - - -<-d-i-v->-C-o-r-p-u-s- -p-r-o-j-e-c-t-<-/-d-i-v->-
- - - - - - - - - - - - -<-d-i-v->-T-r-a-n-s-l-a-t-i-o-n- -n-o-t-e-s-<-/-d-i-v->-
- - - - - - - - - - - - -<-d-i-v->-N-L-P- -p-i-p-e-l-i-n-e-<-/-d-i-v->-
- - - - - - - - - - - - -<-d-i-v->-A-n-n-o-t-a-t-i-o-n- -p-l-a-n-<-/-d-i-v->-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---p-a-p-e-r-"->-
- - - - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - - - -M-a-d-e- -f-o-r- -<-s-p-a-n->-l-a-n-g-u-a-g-e- -r-e-s-e-a-r-c-h-e-r-s-<-/-s-p-a-n->-
- - - - - - - - - - -<-/-h-2->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---m-a-d-e---c-a-r-d-s-"->-
- - - - - - - - - - - - -{-c-a-r-d-s-.-m-a-p-(-(-c-a-r-d-)- -=->- -(-
- - - - - - - - - - - - - - -<-a-r-t-i-c-l-e- -k-e-y-=-{-c-a-r-d-.-t-i-t-l-e-}- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - - - - - - - -<-h-3->-{-c-a-r-d-.-t-i-t-l-e-}-<-/-h-3->-
- - - - - - - - - - - - - - - - -<-p->-{-c-a-r-d-.-b-o-d-y-}-<-/-p->-
- - - - - - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
- - - - - - - - - - - - -)-)-}-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}--
-
-f-u-n-c-t-i-o-n- -P-r-i-m-a-r-y-V-i-d-e-o-S-t-a-g-e-(-{-
- - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-,-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-,-
-}-:- -{-
- - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-:- -a-n-y-[-]-;-
- - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-:- -b-o-o-l-e-a-n-;-
-}-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-p-r-i-m-a-r-y---v-i-d-e-o-s-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---d-o-o-d-l-e- -l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---l-e-f-t-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -2-2-0- -1-7-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-3-4- -1-2-6-h-1-1-8-M-4-7- -1-0-2-h-8-8-M-6-1- -7-8-h-6-2-M-5-1- -4-8-h-8-4-l-2-4- -5-8---2-4- -3-8-H-5-1-L-2-9- -1-0-3-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-4-2- -1-0-2-h-4-8-M-1-6-5- -8-2-l-2-8- -2-0---2-8- -2-0-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---d-o-o-d-l-e- -l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---r-i-g-h-t-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-v-g- -v-i-e-w-B-o-x-=-"-0- -0- -2-2-0- -1-8-0-"->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-1-2- -1-4-2-V-4-5-M-1-1-2- -4-5-l-4-5- -2-8-M-1-1-2- -4-5- -6-6- -7-6-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-7-6- -8-9-c---2-1---1-8---4-7- -1-1---2-0- -3-4- -8- -7- -2-0- -1-3- -2-0- -1-3-s-1-5---1-0- -2-2---2-1-c-8---1-3---7---2-5---2-2---2-6-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-1-4-1- -8-9-c-2-1---1-8- -4-7- -1-1- -2-0- -3-4---8- -7---2-0- -1-3---2-0- -1-3-s---1-5---1-0---2-2---2-1-c---8---1-3- -7---2-5- -2-2---2-6-Z-"- -/->-
- - - - - - - - - - -<-p-a-t-h- -d-=-"-M-7-5- -1-5-4-h-7-5-"- -/->-
- - - - - - - - -<-/-s-v-g->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---h-e-a-d- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -<-p->-V-i-d-e-o- -s-t-u-d-i-o-<-/-p->-
- - - - - - - - - - -<-h-2->-W-a-t-c-h- -h-o-w- -l-a-n-g-u-a-g-e- -d-a-t-a- -b-e-c-o-m-e-s- -r-e-s-e-a-r-c-h-.-<-/-h-2->-
- - - - - - - - - - -<-s-p-a-n->-
- - - - - - - - - - - - -C-o-u-r-s-e-s-,- -w-o-r-k-s-h-o-p-s-,- -d-e-m-o-s-,- -a-n-d- -A-I-/-N-L-P- -w-o-r-k-f-l-o-w-s- -a-p-p-e-a-r- -h-e-r-e- -a-s- -a-
- - - - - - - - - - - - -p-r-i-m-a-r-y- -v-i-s-u-a-l- -s-e-c-t-i-o-n-.-
- - - - - - - - - - -<-/-s-p-a-n->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---s-h-e-l-l- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - -<-H-o-m-e-M-e-d-i-a-S-h-o-w-c-a-s-e-
- - - - - - - - - - - - -v-i-d-e-o-s-=-{-h-o-m-e-p-a-g-e-V-i-d-e-o-s-}-
- - - - - - - - - - - - -c-a-n-M-a-n-a-g-e-=-{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-}-
- - - - - - - - - - -/->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---p-r-i-m-a-r-y---v-i-d-e-o---a-c-t-i-o-n-s- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-w-o-r-k-s-h-o-p-s-"->-U-p-c-o-m-i-n-g- -w-o-r-k-s-h-o-p-s- ---&-g-t-;-<-/-L-i-n-k->-
- - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-c-o-u-r-s-e-s-"->-B-r-o-w-s-e- -c-o-u-r-s-e-s- ---&-g-t-;-<-/-L-i-n-k->-
-
- - - - - - - - - - -{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e- -?- -(-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-m-a-n-a-g-e-r-/-h-o-m-e-p-a-g-e---v-i-d-e-o-s-"->-M-a-n-a-g-e- -h-o-m-e-p-a-g-e- -v-i-d-e-o-s- ---&-g-t-;-<-/-L-i-n-k->-
- - - - - - - - - - -)- -:- -n-u-l-l-}-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}--
-
-f-u-n-c-t-i-o-n- -W-o-r-k-s-h-o-p-F-o-u-n-d-e-r-F-e-a-t-u-r-e-S-e-c-t-i-o-n-(-)- -{-
- - -c-o-n-s-t- -w-o-r-k-s-h-o-p-C-a-r-d-s- -=- -[-
- - - - -{-
- - - - - - -t-a-g-:- -"-W-o-r-k-s-h-o-p- -0-1-"-,-
- - - - - - -t-i-t-l-e-:- -"-A-I- -R-e-s-e-a-r-c-h- -W-o-r-k-f-l-o-w- -B-o-o-t-c-a-m-p-"-,-
- - - - - - -b-o-d-y-:- -"-L-e-a-r-n- -h-o-w- -t-o- -u-s-e- -A-I- -f-o-r- -l-i-t-e-r-a-t-u-r-e- -r-e-v-i-e-w-,- -c-o-d-i-n-g- -s-u-p-p-o-r-t-,- -a-n-n-o-t-a-t-i-o-n- -p-l-a-n-n-i-n-g-,- -a-n-d- -a-c-a-d-e-m-i-c- -w-r-i-t-i-n-g- -w-i-t-h-o-u-t- -l-o-s-i-n-g- -s-c-h-o-l-a-r-l-y- -c-o-n-t-r-o-l-.-"-,-
- - - - - - -h-r-e-f-:- -"-/-w-o-r-k-s-h-o-p-s-"-,-
- - - - -}-,-
- - - - -{-
- - - - - - -t-a-g-:- -"-W-o-r-k-s-h-o-p- -0-2-"-,-
- - - - - - -t-i-t-l-e-:- -"-N-L-P- -f-o-r- -H-u-m-a-n-i-s-t-s-"-,-
- - - - - - -b-o-d-y-:- -"-M-o-v-e- -f-r-o-m- -r-a-w- -t-e-x-t- -t-o- -c-o-r-p-u-s- -c-l-e-a-n-i-n-g-,- -k-e-y-w-o-r-d-s-,- -e-m-b-e-d-d-i-n-g-s-,- -t-o-p-i-c- -m-o-d-e-l-i-n-g-,- -a-n-d- -i-n-t-e-r-p-r-e-t-a-b-l-e- -l-a-n-g-u-a-g-e---d-a-t-a- -a-n-a-l-y-s-i-s-.-"-,-
- - - - - - -h-r-e-f-:- -"-/-w-o-r-k-s-h-o-p-s-"-,-
- - - - -}-,-
- - - - -{-
- - - - - - -t-a-g-:- -"-W-o-r-k-s-h-o-p- -0-3-"-,-
- - - - - - -t-i-t-l-e-:- -"-T-r-a-n-s-l-a-t-i-o-n- -T-e-c-h-n-o-l-o-g-y- -L-a-b-"-,-
- - - - - - -b-o-d-y-:- -"-E-x-p-l-o-r-e- -m-a-c-h-i-n-e- -t-r-a-n-s-l-a-t-i-o-n- -e-v-a-l-u-a-t-i-o-n-,- -t-e-r-m-i-n-o-l-o-g-y- -w-o-r-k-f-l-o-w-s-,- -p-o-s-t---e-d-i-t-i-n-g-,- -a-n-d- -h-u-m-a-n---A-I- -r-e-v-i-s-i-o-n- -p-r-a-c-t-i-c-e-s-.-"-,-
- - - - - - -h-r-e-f-:- -"-/-w-o-r-k-s-h-o-p-s-"-,-
- - - - -}-,-
- - -]-;-
-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---f-o-u-n-d-e-r- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-w-o-r-k-s-h-o-p---f-o-u-n-d-e-r-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---o-r-b-i-t-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - -<-s-p-a-n->-A-I-<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-N-L-P-<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-C-o-r-p-u-s-<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-M-T-<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-D-a-t-a-<-/-s-p-a-n->-
- - - - - - - - -<-s-p-a-n->-R-e-s-e-a-r-c-h-<-/-s-p-a-n->-
- - - - - - -<-/-d-i-v->-
-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---f-o-u-n-d-e-r---h-e-a-d- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -<-p->-W-o-r-k-s-h-o-p-s- -a-n-d- -f-o-u-n-d-e-r- -m-e-s-s-a-g-e-<-/-p->-
- - - - - - - - - - -<-h-2->-
- - - - - - - - - - - - -L-e-a-r-n- -t-h-e- -w-o-r-k-f-l-o-w-.- -K-e-e-p- -t-h-e- -j-u-d-g-m-e-n-t-.-
- - - - - - - - - - -<-/-h-2->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---f-o-u-n-d-e-r---g-r-i-d-"->-
- - - - - - - - - - -<-a-r-t-i-c-l-e- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---f-o-u-n-d-e-r---c-a-r-d- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - - - -<-s-p-a-n->-F-o-u-n-d-e-r- -m-e-s-s-a-g-e-<-/-s-p-a-n->-
-
- - - - - - - - - - - - -<-h-3->-
- - - - - - - - - - - - - - -L-e-x-D-a-t-a- -i-s- -b-u-i-l-t- -f-o-r- -p-e-o-p-l-e- -w-h-o- -w-o-r-k- -s-e-r-i-o-u-s-l-y- -w-i-t-h- -l-a-n-g-u-a-g-e-.-
- - - - - - - - - - - - -<-/-h-3->-
-
- - - - - - - - - - - - -<-p->-
- - - - - - - - - - - - - - -O-u-r- -g-o-a-l- -i-s- -n-o-t- -t-o- -r-e-p-l-a-c-e- -r-e-s-e-a-r-c-h-e-r-s-,- -t-e-a-c-h-e-r-s-,- -t-r-a-n-s-l-a-t-o-r-s-,- -o-r-
- - - - - - - - - - - - - - -s-t-u-d-e-n-t-s- -w-i-t-h- -a-u-t-o-m-a-t-i-o-n-.- -O-u-r- -g-o-a-l- -i-s- -t-o- -g-i-v-e- -t-h-e-m- -b-e-t-t-e-r- -l-a-n-g-u-a-g-e-
- - - - - - - - - - - - - - -d-a-t-a- -w-o-r-k-f-l-o-w-s-:- -c-l-e-a-r-e-r- -c-o-r-p-o-r-a-,- -c-l-e-a-n-e-r- -a-n-n-o-t-a-t-i-o-n-,- -s-m-a-r-t-e-r- -N-L-P-,-
- - - - - - - - - - - - - - -a-n-d- -m-o-r-e- -r-e-s-p-o-n-s-i-b-l-e- -A-I- -u-s-e-.-
- - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - -<-p->-
- - - - - - - - - - - - - - -W-e- -b-e-l-i-e-v-e- -t-h-e- -f-u-t-u-r-e- -o-f- -l-a-n-g-u-a-g-e- -r-e-s-e-a-r-c-h- -b-e-l-o-n-g-s- -t-o- -p-e-o-p-l-e- -w-h-o-
- - - - - - - - - - - - - - -c-a-n- -c-o-m-b-i-n-e- -h-u-m-a-n- -i-n-t-e-r-p-r-e-t-a-t-i-o-n- -w-i-t-h- -c-o-m-p-u-t-a-t-i-o-n-a-l- -m-e-t-h-o-d-s-.-
- - - - - - - - - - - - -<-/-p->-
-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-a-b-o-u-t-"->-R-e-a-d- -o-u-r- -s-t-o-r-y- ---&-g-t-;-<-/-L-i-n-k->-
- - - - - - - - - - -<-/-a-r-t-i-c-l-e->-
-
- - - - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---s-t-a-c-k-"->-
- - - - - - - - - - - - -{-w-o-r-k-s-h-o-p-C-a-r-d-s-.-m-a-p-(-(-i-t-e-m-)- -=->- -(-
- - - - - - - - - - - - - - -<-L-i-n-k- -k-e-y-=-{-i-t-e-m-.-t-i-t-l-e-}- -h-r-e-f-=-{-i-t-e-m-.-h-r-e-f-}- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---c-a-r-d- -p-a-p-e-r---r-e-v- -p-a-p-e-r---t-u-r-n-"->-
- - - - - - - - - - - - - - - - -<-s-m-a-l-l->-{-i-t-e-m-.-t-a-g-}-<-/-s-m-a-l-l->-
- - - - - - - - - - - - - - - - -<-h-3->-{-i-t-e-m-.-t-i-t-l-e-}-<-/-h-3->-
- - - - - - - - - - - - - - - - -<-p->-{-i-t-e-m-.-b-o-d-y-}-<-/-p->-
- - - - - - - - - - - - - - - - -<-b->-V-i-e-w- -w-o-r-k-s-h-o-p- ---&-g-t-;-<-/-b->-
- - - - - - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - - - - - -)-)-}-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-l-e-x---w-o-r-k-s-h-o-p---m-a-r-q-u-e-e- -p-a-p-e-r---r-e-v-"- -a-r-i-a---h-i-d-d-e-n-=-"-t-r-u-e-"->-
- - - - - - - - - - -<-d-i-v->-
- - - - - - - - - - - - -<-s-p-a-n->-A-I- -l-i-t-e-r-a-c-y-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-C-o-r-p-u-s- -m-e-t-h-o-d-s-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-N-L-P- -w-o-r-k-f-l-o-w-s-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-T-r-a-n-s-l-a-t-i-o-n- -t-e-c-h-n-o-l-o-g-y-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-R-e-s-e-a-r-c-h- -w-r-i-t-i-n-g-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-H-u-m-a-n---c-e-n-t-e-r-e-d- -A-I-<-/-s-p-a-n->-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - - - -<-d-i-v->-
- - - - - - - - - - - - -<-s-p-a-n->-A-I- -l-i-t-e-r-a-c-y-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-C-o-r-p-u-s- -m-e-t-h-o-d-s-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-N-L-P- -w-o-r-k-f-l-o-w-s-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-T-r-a-n-s-l-a-t-i-o-n- -t-e-c-h-n-o-l-o-g-y-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-R-e-s-e-a-r-c-h- -w-r-i-t-i-n-g-<-/-s-p-a-n->-
- - - - - - - - - - - - -<-s-p-a-n->-H-u-m-a-n---c-e-n-t-e-r-e-d- -A-I-<-/-s-p-a-n->-
- - - - - - - - - - -<-/-d-i-v->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}--
-f-u-n-c-t-i-o-n- -C-l-o-s-i-n-g-S-e-c-t-i-o-n-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-s-e-c-t-i-o-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---c-l-o-s-i-n-g- -p-a-p-e-r---p-a-g-e-"- -i-d-=-"-c-o-u-r-s-e-s-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-p- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---c-o-u-n-t- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -T-r-u-s-t-e-d- -b-y- -<-s-p-a-n->-h-u-m-a-n- -l-e-a-r-n-e-r-s-<-/-s-p-a-n->-,- -r-e-s-e-a-r-c-h-e-r-s-,- -a-n-d- -e-d-u-c-a-t-o-r-s-.-
- - - - - - - - -<-/-p->-
-
- - - - - - - - -<-h-2- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---r-e-v-"->-G-e-t- -s-t-a-r-t-e-d- -w-i-t-h- -L-e-x-D-a-t-a- -t-o-d-a-y-.-<-/-h-2->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---c-t-a- -p-a-p-e-r---r-e-v-"->-
- - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-t-n- -p-a-p-e-r---b-t-n---c-o-r-a-l-"- -h-r-e-f-=-"-/-w-o-r-k-s-h-o-p-s-"->-
- - - - - - - - - - - - -U-p-c-o-m-i-n-g- -w-o-r-k-s-h-o-p-s-
- - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---b-t-n- -p-a-p-e-r---b-t-n---g-h-o-s-t-"- -h-r-e-f-=-"-/-c-o-u-r-s-e-s-"->-
- - - - - - - - - - - - -B-r-o-w-s-e- -c-o-u-r-s-e-s-
- - - - - - - - - - -<-/-L-i-n-k->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-s-e-c-t-i-o-n->-
- - -)-;-
-}-
-
-f-u-n-c-t-i-o-n- -P-a-p-e-r-F-o-o-t-e-r-(-)- -{-
- - -r-e-t-u-r-n- -(-
- - - - -<-f-o-o-t-e-r- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---f-o-o-t-e-r-"->-
- - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---w-r-a-p-"->-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---f-o-o-t-e-r---c-o-l-s-"->-
- - - - - - - - - - -<-d-i-v->-
- - - - - - - - - - - - -<-L-i-n-k- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---f-o-o-t-e-r---l-o-g-o-"- -h-r-e-f-=-"-/-"->-
- - - - - - - - - - - - - - -L-e-x-D-a-t-a-.-.-.-
- - - - - - - - - - - - -<-/-L-i-n-k->-
-
- - - - - - - - - - - - -<-p->-
- - - - - - - - - - - - - - -I-n-t-e-l-l-i-g-e-n-t- -d-a-t-a- -s-o-l-u-t-i-o-n-s- -f-o-r- -l-a-n-g-u-a-g-e-,- -t-r-a-n-s-l-a-t-i-o-n-,- -e-d-u-c-a-t-i-o-n-,-
- - - - - - - - - - - - - - -a-n-d- -s-o-c-i-e-t-y-.-
- - - - - - - - - - - - -<-/-p->-
- - - - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - - - -<-n-a-v->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-a-b-o-u-t-"->-A-b-o-u-t-<-/-L-i-n-k->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-s-e-r-v-i-c-e-s-"->-S-e-r-v-i-c-e-s-<-/-L-i-n-k->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-c-o-u-r-s-e-s-"->-C-o-u-r-s-e-s-<-/-L-i-n-k->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-w-o-r-k-s-h-o-p-s-"->-W-o-r-k-s-h-o-p-s-<-/-L-i-n-k->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-c-o-n-t-a-c-t-"->-C-o-n-t-a-c-t-<-/-L-i-n-k->-
- - - - - - - - - - - - -<-L-i-n-k- -h-r-e-f-=-"-/-d-a-s-h-b-o-a-r-d-"->-D-a-s-h-b-o-a-r-d-<-/-L-i-n-k->-
- - - - - - - - - - -<-/-n-a-v->-
-
- - - - - - - - - - -<-b-l-o-c-k-q-u-o-t-e->-
- - - - - - - - - - - - -T-h-e- -l-i-m-i-t-s- -o-f- -m-y- -l-a-n-g-u-a-g-e- -m-e-a-n- -t-h-e- -l-i-m-i-t-s- -o-f- -m-y- -w-o-r-l-d-.-
- - - - - - - - - - - - -<-c-i-t-e->--- -L-u-d-w-i-g- -W-i-t-t-g-e-n-s-t-e-i-n-<-/-c-i-t-e->-
- - - - - - - - - - -<-/-b-l-o-c-k-q-u-o-t-e->-
- - - - - - - - -<-/-d-i-v->-
-
- - - - - - - - -<-d-i-v- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---f-o-o-t-e-r---b-o-t-t-o-m-"->-
- - - - - - - - - - -<-s-p-a-n->-婵-?-2-0-2-6- -L-e-x-D-a-t-a-<-/-s-p-a-n->-
- - - - - - - - - - -<-s-p-a-n->-m-a-d-e- -b-y- -h-u-m-a-n-s-<-/-s-p-a-n->-
- - - - - - - - -<-/-d-i-v->-
- - - - - - -<-/-d-i-v->-
- - - - -<-/-f-o-o-t-e-r->-
- - -)-;-
-}-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -I-n-t-e-g-r-a-t-e-d-H-o-m-e-P-a-g-e-(-)- -{-
- - -c-o-n-s-t- -a-d-m-i-n- -=- -c-r-e-a-t-e-A-d-m-i-n-C-l-i-e-n-t-(-)-;-
-
- - -l-e-t- -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e- -=- -f-a-l-s-e-;-
- - -l-e-t- -h-o-m-e-p-a-g-e-V-i-d-e-o-s-:- -a-n-y-[-]- -=- -[-]-;-
-
- - -l-e-t- -s-t-a-t-s-:- -S-t-a-t-C-a-r-d-[-]- -=- -[-
- - - - -{- -l-a-b-e-l-:- -"-P-u-b-l-i-s-h-e-d- -c-o-u-r-s-e-s-"-,- -v-a-l-u-e-:- -0-,- -h-r-e-f-:- -"-/-c-o-u-r-s-e-s-"- -}-,-
- - - - -{- -l-a-b-e-l-:- -"-A-c-t-i-v-e- -w-o-r-k-s-h-o-p-s-"-,- -v-a-l-u-e-:- -0-,- -h-r-e-f-:- -"-/-w-o-r-k-s-h-o-p-s-"- -}-,-
- - - - -{- -l-a-b-e-l-:- -"-V-i-d-e-o- -h-i-g-h-l-i-g-h-t-s-"-,- -v-a-l-u-e-:- -0-,- -h-r-e-f-:- -"-#-v-i-d-e-o-s-"- -}-,-
- - - - -{- -l-a-b-e-l-:- -"-T-e-a-m- -m-e-m-b-e-r-s-"-,- -v-a-l-u-e-:- -0-,- -h-r-e-f-:- -"-/-t-e-a-m-"- -}-,-
- - -]-;-
-
- - -c-o-n-s-t- -s-l-o-t-s- -=- -a-w-a-i-t- -g-e-t-H-o-m-e-p-a-g-e-C-o-n-t-e-n-t-S-l-o-t-s-(-)-;-
-
- - -t-r-y- -{-
- - - - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - - - -c-o-n-s-t- -{-
- - - - - - -d-a-t-a-:- -{- -u-s-e-r- -}-,-
- - - - - - -e-r-r-o-r-:- -u-s-e-r-E-r-r-o-r-,-
- - - - -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-a-u-t-h-.-g-e-t-U-s-e-r-(-)-;-
-
- - - - -i-f- -(-!-u-s-e-r-E-r-r-o-r- -&-&- -u-s-e-r-)- -{-
- - - - - - -c-o-n-s-t- -{- -d-a-t-a-:- -p-r-o-f-i-l-e-,- -e-r-r-o-r-:- -p-r-o-f-i-l-e-E-r-r-o-r- -}- -=- -a-w-a-i-t- -a-d-m-i-n-
- - - - - - - - -.-f-r-o-m-(-"-p-r-o-f-i-l-e-s-"-)-
- - - - - - - - -.-s-e-l-e-c-t-(-"-r-o-l-e-"-)-
- - - - - - - - -.-e-q-(-"-i-d-"-,- -u-s-e-r-.-i-d-)-
- - - - - - - - -.-m-a-y-b-e-S-i-n-g-l-e-(-)-;-
-
- - - - - - -i-f- -(-!-p-r-o-f-i-l-e-E-r-r-o-r-)- -{-
- - - - - - - - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e- -=-
- - - - - - - - - - -p-r-o-f-i-l-e-?-.-r-o-l-e- -=-=-=- -"-a-d-m-i-n-"- -|-|- -p-r-o-f-i-l-e-?-.-r-o-l-e- -=-=-=- -"-m-a-n-a-g-e-r-"-;-
- - - - - - -}-
- - - - -}-
-
- - - - -l-e-t- -h-o-m-e-p-a-g-e-V-i-d-e-o-s-Q-u-e-r-y- -=- -a-d-m-i-n-
- - - - - - -.-f-r-o-m-(-"-h-o-m-e-p-a-g-e-_-v-i-d-e-o-s-"-)-
- - - - - - -.-s-e-l-e-c-t-(-"-*-"-)-
- - - - - - -.-o-r-d-e-r-(-"-d-i-s-p-l-a-y-_-o-r-d-e-r-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -t-r-u-e- -}-)-
- - - - - - -.-o-r-d-e-r-(-"-c-r-e-a-t-e-d-_-a-t-"-,- -{- -a-s-c-e-n-d-i-n-g-:- -f-a-l-s-e- -}-)-;-
-
- - - - -i-f- -(-!-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-)- -{-
- - - - - - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-Q-u-e-r-y- -=- -h-o-m-e-p-a-g-e-V-i-d-e-o-s-Q-u-e-r-y-.-e-q-(-"-i-s-_-a-c-t-i-v-e-"-,- -t-r-u-e-)-;-
- - - - -}-
-
- - - - -c-o-n-s-t- -{- -d-a-t-a-:- -v-i-d-e-o-s-D-a-t-a-,- -e-r-r-o-r-:- -v-i-d-e-o-s-E-r-r-o-r- -}- -=- -a-w-a-i-t- -h-o-m-e-p-a-g-e-V-i-d-e-o-s-Q-u-e-r-y-;-
-
- - - - -i-f- -(-!-v-i-d-e-o-s-E-r-r-o-r-)- -{-
- - - - - - -h-o-m-e-p-a-g-e-V-i-d-e-o-s- -=- -v-i-d-e-o-s-D-a-t-a- -?-?- -[-]-;-
- - - - -}-
-
- - - - -c-o-n-s-t- -[-c-o-u-r-s-e-s-C-o-u-n-t-,- -w-o-r-k-s-h-o-p-s-C-o-u-n-t-,- -v-i-d-e-o-s-C-o-u-n-t-,- -t-e-a-m-C-o-u-n-t-]- -=-
- - - - - - -a-w-a-i-t- -P-r-o-m-i-s-e-.-a-l-l-(-[-
- - - - - - - - -a-d-m-i-n-
- - - - - - - - - - -.-f-r-o-m-(-"-c-o-u-r-s-e-s-"-)-
- - - - - - - - - - -.-s-e-l-e-c-t-(-"-i-d-"-,- -{- -c-o-u-n-t-:- -"-e-x-a-c-t-"-,- -h-e-a-d-:- -t-r-u-e- -}-)-
- - - - - - - - - - -.-e-q-(-"-i-s-_-p-u-b-l-i-s-h-e-d-"-,- -t-r-u-e-)-,-
-
- - - - - - - - -a-d-m-i-n-
- - - - - - - - - - -.-f-r-o-m-(-"-w-o-r-k-s-h-o-p-s-"-)-
- - - - - - - - - - -.-s-e-l-e-c-t-(-"-i-d-"-,- -{- -c-o-u-n-t-:- -"-e-x-a-c-t-"-,- -h-e-a-d-:- -t-r-u-e- -}-)-
- - - - - - - - - - -.-e-q-(-"-i-s-_-p-u-b-l-i-s-h-e-d-"-,- -t-r-u-e-)-,-
-
- - - - - - - - -a-d-m-i-n-
- - - - - - - - - - -.-f-r-o-m-(-"-h-o-m-e-p-a-g-e-_-v-i-d-e-o-s-"-)-
- - - - - - - - - - -.-s-e-l-e-c-t-(-"-i-d-"-,- -{- -c-o-u-n-t-:- -"-e-x-a-c-t-"-,- -h-e-a-d-:- -t-r-u-e- -}-)-
- - - - - - - - - - -.-e-q-(-"-i-s-_-a-c-t-i-v-e-"-,- -t-r-u-e-)-,-
-
- - - - - - - - -a-d-m-i-n-
- - - - - - - - - - -.-f-r-o-m-(-"-t-e-a-m-_-m-e-m-b-e-r-s-"-)-
- - - - - - - - - - -.-s-e-l-e-c-t-(-"-i-d-"-,- -{- -c-o-u-n-t-:- -"-e-x-a-c-t-"-,- -h-e-a-d-:- -t-r-u-e- -}-)-
- - - - - - - - - - -.-e-q-(-"-i-s-_-a-c-t-i-v-e-"-,- -t-r-u-e-)-,-
- - - - - - -]-)-;-
-
- - - - -s-t-a-t-s- -=- -[-
- - - - - - -{- -l-a-b-e-l-:- -"-P-u-b-l-i-s-h-e-d- -c-o-u-r-s-e-s-"-,- -v-a-l-u-e-:- -c-o-u-r-s-e-s-C-o-u-n-t-.-c-o-u-n-t- -?-?- -0-,- -h-r-e-f-:- -"-/-c-o-u-r-s-e-s-"- -}-,-
- - - - - - -{- -l-a-b-e-l-:- -"-A-c-t-i-v-e- -w-o-r-k-s-h-o-p-s-"-,- -v-a-l-u-e-:- -w-o-r-k-s-h-o-p-s-C-o-u-n-t-.-c-o-u-n-t- -?-?- -0-,- -h-r-e-f-:- -"-/-w-o-r-k-s-h-o-p-s-"- -}-,-
- - - - - - -{- -l-a-b-e-l-:- -"-V-i-d-e-o- -h-i-g-h-l-i-g-h-t-s-"-,- -v-a-l-u-e-:- -v-i-d-e-o-s-C-o-u-n-t-.-c-o-u-n-t- -?-?- -0-,- -h-r-e-f-:- -"-#-v-i-d-e-o-s-"- -}-,-
- - - - - - -{- -l-a-b-e-l-:- -"-T-e-a-m- -m-e-m-b-e-r-s-"-,- -v-a-l-u-e-:- -t-e-a-m-C-o-u-n-t-.-c-o-u-n-t- -?-?- -0-,- -h-r-e-f-:- -"-/-t-e-a-m-"- -}-,-
- - - - -]-;-
- - -}- -c-a-t-c-h- -(-e-r-r-o-r-)- -{-
- - - - -c-o-n-s-o-l-e-.-e-r-r-o-r-(-"-I-n-t-e-g-r-a-t-e-d- -h-o-m-e-p-a-g-e- -e-r-r-o-r-:-"-,- -e-r-r-o-r-)-;-
- - - - -h-o-m-e-p-a-g-e-V-i-d-e-o-s- -=- -[-]-;-
- - - - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e- -=- -f-a-l-s-e-;-
- - -}-
-
- - -r-e-t-u-r-n- -(-
- - - - -<->-
- - - - - - -<-H-o-m-e-C-o-n-t-r-o-l-P-a-n-e-l-B-u-t-t-o-n- -/->-
-
- - - - - - -<-m-a-i-n- -c-l-a-s-s-N-a-m-e-=-"-p-a-p-e-r---h-o-m-e-"->-
- - - - - - - - -<-H-e-r-o-S-e-c-t-i-o-n- -s-l-o-t-s-=-{-s-l-o-t-s-}- -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-=-{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-}- -/->-
- - - - - - - - -<-S-t-r-i-p-S-e-c-t-i-o-n- -/->-
- - - - - - - - -<-D-y-n-a-m-i-c-P-o-s-t-e-r-S-l-i-d-e-r- -/->--
- - - - - - - - -<-L-e-x-D-a-t-a-D-a-r-k-S-t-o-r-y-S-e-c-t-i-o-n- -/->--
- - - - - - - - -<-P-r-e-v-i-o-u-s-C-a-s-e-s-S-h-o-w-c-a-s-e- -/->--
- - - - - - - - -<-L-e-x-D-a-t-a-M-a-n-i-f-e-s-t-o-S-e-c-t-i-o-n- -/->-
-<-P-a-p-e-r-P-a-n-e-l-
- - - - - - - - - - -i-d-=-"-s-h-o-w-c-a-s-e-"-
- - - - - - - - - - -k-i-c-k-e-r-=-"-H-o-m-e-p-a-g-e- -s-h-o-w-c-a-s-e-"-
- - - - - - - - - - -t-i-t-l-e-=-"-F-e-a-t-u-r-e-d- -L-e-x-D-a-t-a- -a-n-n-o-u-n-c-e-m-e-n-t-s- -a-n-d- -h-i-g-h-l-i-g-h-t-s-.-"-
- - - - - - - - ->-
- - - - - - - - - - -<-D-y-n-a-m-i-c-H-o-m-e-S-h-o-w-c-a-s-e- -/->-
- - - - - - - - -<-/-P-a-p-e-r-P-a-n-e-l->-
-
- - - - - - - - -<-P-a-p-e-r-P-a-n-e-l-
- - - - - - - - - - -i-d-=-"-c-o-u-r-s-e-s-"-
- - - - - - - - - - -k-i-c-k-e-r-=-"-H-i-g-h-l-i-g-h-t-e-d- -c-o-u-r-s-e-s-"-
- - - - - - - - - - -t-i-t-l-e-=-"-F-e-a-t-u-r-e-d- -c-o-u-r-s-e-s- -f-r-o-m- -y-o-u-r- -c-o-u-r-s-e- -d-a-s-h-b-o-a-r-d-.-"-
- - - - - - - - ->-
- - - - - - - - - - -<-H-o-m-e-H-i-g-h-l-i-g-h-t-e-d-C-o-u-r-s-e-s- -/->-
- - - - - - - - -<-/-P-a-p-e-r-P-a-n-e-l->-
-
- - - - - - - - -<-L-e-x-D-a-t-a-R-e-s-e-a-r-c-h-T-o-o-l-s-S-e-c-t-i-o-n- -/->--
--
- - - - - - - - -<-P-r-i-m-a-r-y-V-i-d-e-o-S-t-a-g-e--
- - - - - - - - - - -h-o-m-e-p-a-g-e-V-i-d-e-o-s-=-{-h-o-m-e-p-a-g-e-V-i-d-e-o-s-}--
- - - - - - - - - - -c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-=-{-c-a-n-M-a-n-a-g-e-H-o-m-e-p-a-g-e-}--
- - - - - - - - -/->-
-
- - - - - - - - -<-L-a-t-e-s-t-E-v-e-n-t-s-H-o-m-e-S-e-c-t-i-o-n- -/->--
--
- - - - - - - - -<-M-e-s-s-a-g-e-S-e-c-t-i-o-n- -s-l-o-t-s-=-{-s-l-o-t-s-}- -/->-
- - - - - - - - -<-S-t-a-n-c-e-B-a-n-d- -/->-
-
- - - - - - - - -<-P-a-p-e-r-P-a-n-e-l- -i-d-=-"-n-l-p-"- -k-i-c-k-e-r-=-"-N-L-P- -a-t-t-r-a-c-t-i-o-n-"- -t-i-t-l-e-=-"-W-h-y- -l-a-n-g-u-a-g-e- -d-a-t-a- -m-a-t-t-e-r-s-.-"->-
- - - - - - - - - - -<-N-l-p-A-t-t-r-a-c-t-i-o-n-S-e-c-t-i-o-n- -/->-
- - - - - - - - -<-/-P-a-p-e-r-P-a-n-e-l->-
-
- - - - - - - - -<-P-a-p-e-r-P-a-n-e-l-
- - - - - - - - - - -i-d-=-"-c-o-l-l-a-b-o-r-a-t-i-o-n-"-
- - - - - - - - - - -k-i-c-k-e-r-=-"-C-o-l-l-a-b-o-r-a-t-i-o-n-"-
- - - - - - - - - - -t-i-t-l-e-=-"-P-a-r-t-n-e-r-s-h-i-p-s-,- -M-o-U-s-,- -a-n-d- -a-c-a-d-e-m-i-c- -c-o-o-p-e-r-a-t-i-o-n-.-"-
- - - - - - - - ->-
- - - - - - - - - - -<-M-o-u-C-o-l-l-a-b-o-r-a-t-i-o-n-S-e-c-t-i-o-n- -/->-
- - - - - - - - -<-/-P-a-p-e-r-P-a-n-e-l->-
-
-
-
- - - - - - - - -<-C-l-o-s-i-n-g-S-e-c-t-i-o-n- -/->-
- - - - - - - - -<-P-a-p-e-r-F-o-o-t-e-r- -/->-
- - - - - - -<-/-m-a-i-n->-
- - - - -<-/->-
- - -)-;-
-}-