-i-m-p-o-r-t- -{- -r-e-d-i-r-e-c-t- -}- -f-r-o-m- -"-n-e-x-t-/-n-a-v-i-g-a-t-i-o-n-"-;-
-
-e-x-p-o-r-t- -d-e-f-a-u-l-t- -f-u-n-c-t-i-o-n- -S-i-g-n-u-p-P-a-g-e-(-)- -{-
- - -r-e-d-i-r-e-c-t-(-"-/-l-o-g-i-n-"-)-;-
-}-