-- LexData registered workshop livestream system

create table if not exists public.workshop_live_streams (
  id uuid primary key default gen_random_uuid(),
  workshop_id uuid not null unique references public.workshops(id) on delete cascade,
  provider text not null default 'cloudflare',
  title text,
  live_input_uid text not null unique,
  rtmps_url text,
  stream_key text,
  customer_code text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'waiting', 'live', 'ended', 'cancelled')),
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  recording_uid text,
  is_enabled boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workshop_live_streams_workshop_idx
  on public.workshop_live_streams(workshop_id);

create index if not exists workshop_live_streams_status_idx
  on public.workshop_live_streams(status);

create table if not exists public.live_chat_messages (
  id bigint generated by default as identity primary key,
  stream_id uuid not null references public.workshop_live_streams(id) on delete cascade,
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  body text not null check (char_length(body) between 1 and 500),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists live_chat_messages_stream_created_idx
  on public.live_chat_messages(stream_id, created_at desc);

create table if not exists public.live_attendance (
  id uuid primary key default gen_random_uuid(),
  stream_id uuid not null references public.workshop_live_streams(id) on delete cascade,
  workshop_id uuid not null references public.workshops(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  left_at timestamptz,
  watch_seconds integer not null default 0 check (watch_seconds >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(stream_id, user_id)
);

create index if not exists live_attendance_stream_seen_idx
  on public.live_attendance(stream_id, last_seen_at desc);

alter table public.workshop_live_streams enable row level security;
alter table public.live_chat_messages enable row level security;
alter table public.live_attendance enable row level security;

notify pgrst, 'reload schema';
