-"-u-s-e- -s-e-r-v-e-r-"-;-
-
-i-m-p-o-r-t- -{- -r-e-v-a-l-i-d-a-t-e-P-a-t-h- -}- -f-r-o-m- -"-n-e-x-t-/-c-a-c-h-e-"-;-
-i-m-p-o-r-t- -{- -r-e-d-i-r-e-c-t- -}- -f-r-o-m- -"-n-e-x-t-/-n-a-v-i-g-a-t-i-o-n-"-;-
-i-m-p-o-r-t- -{- -r-e-q-u-i-r-e-A-d-m-i-n- -}- -f-r-o-m- -"-@-/-l-i-b-/-a-u-t-h-"-;-
-i-m-p-o-r-t- -{- -c-r-e-a-t-e-C-l-i-e-n-t- -}- -f-r-o-m- -"-@-/-l-i-b-/-s-u-p-a-b-a-s-e-/-s-e-r-v-e-r-"-;-
-i-m-p-o-r-t- -{- -u-p-l-o-a-d-I-m-a-g-e-F-r-o-m-F-o-r-m-D-a-t-a- -}- -f-r-o-m- -"-@-/-l-i-b-/-u-p-l-o-a-d-"-;-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -c-r-e-a-t-e-H-i-g-h-l-i-g-h-t-(-f-o-r-m-D-a-t-a-:- -F-o-r-m-D-a-t-a-)- -{-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -l-e-t- -i-m-a-g-e-U-r-l-:- -s-t-r-i-n-g- -|- -n-u-l-l- -=- -n-u-l-l-;-
-
- - -t-r-y- -{-
- - - - -i-m-a-g-e-U-r-l- -=- -a-w-a-i-t- -u-p-l-o-a-d-I-m-a-g-e-F-r-o-m-F-o-r-m-D-a-t-a-(-
- - - - - - -f-o-r-m-D-a-t-a-,-
- - - - - - -"-i-m-a-g-e-_-f-i-l-e-"-,-
- - - - - - -"-s-e-s-s-i-o-n---h-i-g-h-l-i-g-h-t-s-"-
- - - - -)-;-
- - -}- -c-a-t-c-h- -(-e-r-r-o-r-)- -{-
- - - - -c-o-n-s-t- -m-e-s-s-a-g-e- -=-
- - - - - - -e-r-r-o-r- -i-n-s-t-a-n-c-e-o-f- -E-r-r-o-r- -?- -e-r-r-o-r-.-m-e-s-s-a-g-e- -:- -"-I-m-a-g-e- -u-p-l-o-a-d- -f-a-i-l-e-d-"-;-
- - - - -r-e-d-i-r-e-c-t-(-`-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-m-e-s-s-a-g-e-)-}-`-)-;-
- - -}-
-
- - -c-o-n-s-t- -{- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-.-f-r-o-m-(-"-s-e-s-s-i-o-n-_-h-i-g-h-l-i-g-h-t-s-"-)-.-i-n-s-e-r-t-(-{-
- - - - -t-i-t-l-e-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-t-i-t-l-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)-,-
- - - - -s-u-b-t-i-t-l-e-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-u-b-t-i-t-l-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -d-e-s-c-r-i-p-t-i-o-n-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-d-e-s-c-r-i-p-t-i-o-n-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -s-e-s-s-i-o-n-_-d-a-t-e-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-e-s-s-i-o-n-_-d-a-t-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -i-m-a-g-e-_-u-r-l-:- -i-m-a-g-e-U-r-l-,-
- - - - -v-i-d-e-o-_-u-r-l-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-v-i-d-e-o-_-u-r-l-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -l-o-c-a-t-i-o-n-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-l-o-c-a-t-i-o-n-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -s-t-a-t-_-l-a-b-e-l-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-t-a-t-_-l-a-b-e-l-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -s-t-a-t-_-v-a-l-u-e-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-t-a-t-_-v-a-l-u-e-"-)- -|-|- -"-"-)-.-t-r-i-m-(-)- -|-|- -n-u-l-l-,-
- - - - -c-t-a-_-l-a-b-e-l-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-t-a-_-l-a-b-e-l-"-)- -|-|- -"-V-i-e-w- -M-o-r-e-"-)-.-t-r-i-m-(-)-,-
- - - - -c-t-a-_-h-r-e-f-:- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-c-t-a-_-h-r-e-f-"-)- -|-|- -"-/-w-o-r-k-s-h-o-p-s-"-)-.-t-r-i-m-(-)-,-
- - - - -s-o-r-t-_-o-r-d-e-r-:- -N-u-m-b-e-r-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-s-o-r-t-_-o-r-d-e-r-"-)- -|-|- -0-)-,-
- - - - -i-s-_-a-c-t-i-v-e-:- -f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-s-_-a-c-t-i-v-e-"-)- -=-=-=- -"-o-n-"-,-
- - -}-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-`-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-e-r-r-o-r-.-m-e-s-s-a-g-e-)-}-`-)-;-
- - -}-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-"-)-;-
-
- - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-?-m-e-s-s-a-g-e-=-H-i-g-h-l-i-g-h-t- -c-r-e-a-t-e-d-"-)-;-
-}-
-
-e-x-p-o-r-t- -a-s-y-n-c- -f-u-n-c-t-i-o-n- -d-e-l-e-t-e-H-i-g-h-l-i-g-h-t-(-f-o-r-m-D-a-t-a-:- -F-o-r-m-D-a-t-a-)- -{-
- - -a-w-a-i-t- -r-e-q-u-i-r-e-A-d-m-i-n-(-)-;-
-
- - -c-o-n-s-t- -i-d- -=- -S-t-r-i-n-g-(-f-o-r-m-D-a-t-a-.-g-e-t-(-"-i-d-"-)- -|-|- -"-"-)-;-
- - -c-o-n-s-t- -s-u-p-a-b-a-s-e- -=- -a-w-a-i-t- -c-r-e-a-t-e-C-l-i-e-n-t-(-)-;-
-
- - -c-o-n-s-t- -{- -e-r-r-o-r- -}- -=- -a-w-a-i-t- -s-u-p-a-b-a-s-e-
- - - - -.-f-r-o-m-(-"-s-e-s-s-i-o-n-_-h-i-g-h-l-i-g-h-t-s-"-)-
- - - - -.-d-e-l-e-t-e-(-)-
- - - - -.-e-q-(-"-i-d-"-,- -i-d-)-;-
-
- - -i-f- -(-e-r-r-o-r-)- -{-
- - - - -r-e-d-i-r-e-c-t-(-`-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-?-m-e-s-s-a-g-e-=-$-{-e-n-c-o-d-e-U-R-I-C-o-m-p-o-n-e-n-t-(-e-r-r-o-r-.-m-e-s-s-a-g-e-)-}-`-)-;-
- - -}-
-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-"-)-;-
- - -r-e-v-a-l-i-d-a-t-e-P-a-t-h-(-"-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-"-)-;-
-
- - -r-e-d-i-r-e-c-t-(-"-/-a-d-m-i-n-/-h-i-g-h-l-i-g-h-t-s-?-m-e-s-s-a-g-e-=-H-i-g-h-l-i-g-h-t- -d-e-l-e-t-e-d-"-)-;-
-}-